import type {
  KlyxProviderDescriptor,
  KlyxProviderId,
} from "./contracts";

export const KLYX_PROVIDER_CATALOG: readonly KlyxProviderDescriptor[] = [
  {
    id: "openai",
    capabilities: ["assistant_reasoning", "structured_llm", "vision"],
    category: "replaceable-runtime",
    criticality: "important",
    serverAuthorityRequired: true,
    clientExposure: "none",
    failureMode: "degraded-local",
    replacementMode: "runtime-adapter",
    fallback: "Deterministic KLYX intent fallback with no automatic execution.",
    productionPolicy: "LLM output is advisory only; deterministic server code owns every sensitive mutation.",
    secretEnvironmentVariables: ["OPENAI_API_KEY"],
    publicEnvironmentVariables: [],
  },
  {
    id: "supabase",
    capabilities: ["postgres", "auth", "storage", "realtime", "durable_state"],
    category: "infrastructure",
    criticality: "critical",
    serverAuthorityRequired: true,
    clientExposure: "publishable-rls-bounded",
    failureMode: "fail-closed",
    replacementMode: "planned-infrastructure-migration",
    fallback: "Isolated restore/DR and local Supabase for certification; no transparent production write failover.",
    productionPolicy: "Browser access is limited to publishable credentials plus RLS/Auth. Privileged mutations remain server-only.",
    secretEnvironmentVariables: ["SUPABASE_SECRET_KEY", "SUPABASE_SERVICE_ROLE_KEY"],
    publicEnvironmentVariables: [
      "NEXT_PUBLIC_SUPABASE_URL",
      "NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY",
      "NEXT_PUBLIC_SUPABASE_ANON_KEY",
    ],
  },
  {
    id: "stripe",
    capabilities: ["payments", "connect", "refunds", "transfers", "reversals", "payout_projection"],
    category: "replaceable-runtime",
    criticality: "critical",
    serverAuthorityRequired: true,
    clientExposure: "none",
    failureMode: "fail-closed",
    replacementMode: "runtime-adapter",
    fallback: "No automatic provider switch for in-flight money. Reconcile external state, then human_review when truth cannot be proved.",
    productionPolicy: "Stripe executes external money operations only after KLYX ledger, eligibility, LIVE authority and exact-SHA gates approve them.",
    secretEnvironmentVariables: ["STRIPE_SECRET_KEY", "STRIPE_WEBHOOK_SECRET"],
    publicEnvironmentVariables: ["NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY"],
  },
  {
    id: "sumsub",
    capabilities: ["kyc", "kyb", "identity_verification"],
    category: "client-assisted",
    criticality: "important",
    serverAuthorityRequired: true,
    clientExposure: "public-sdk-tokenized",
    failureMode: "fail-closed",
    replacementMode: "runtime-adapter",
    fallback: "human_review/manual verification; never treat provider unavailability as verified identity.",
    productionPolicy: "The browser may run the vendor SDK only with a short-lived token issued by KLYX server authority.",
    secretEnvironmentVariables: [
      "SUMSUB_APP_TOKEN",
      "SUMSUB_SECRET_KEY",
      "SUMSUB_WEBHOOK_SECRET",
    ],
    publicEnvironmentVariables: [],
  },
  {
    id: "twilio",
    capabilities: ["phone_otp"],
    category: "replaceable-runtime",
    criticality: "important",
    serverAuthorityRequired: true,
    clientExposure: "none",
    failureMode: "fail-closed",
    replacementMode: "runtime-adapter",
    fallback: "Alternative verification flow may be selected by KLYX policy; an unavailable OTP provider never marks a phone verified.",
    productionPolicy: "OTP send/check are server-only and rate-limited by KLYX state before the provider is called.",
    secretEnvironmentVariables: [
      "TWILIO_API_KEY_SECRET",
      "TWILIO_AUTH_TOKEN",
    ],
    publicEnvironmentVariables: [],
  },
  {
    id: "resend",
    capabilities: ["transactional_email", "operational_alert_email"],
    category: "replaceable-runtime",
    criticality: "important",
    serverAuthorityRequired: true,
    clientExposure: "none",
    failureMode: "defer-and-retry",
    replacementMode: "runtime-adapter",
    fallback: "Durable delivery registry keeps business truth independent from email delivery; failed delivery can be retried or surfaced operationally.",
    productionPolicy: "Email is a side effect, not a source of truth. Provider idempotency keys are derived from KLYX delivery state.",
    secretEnvironmentVariables: ["RESEND_API_KEY"],
    publicEnvironmentVariables: [],
  },
  {
    id: "tolgee",
    capabilities: ["translation_management"],
    category: "control-plane",
    criticality: "optional",
    serverAuthorityRequired: false,
    clientExposure: "none",
    failureMode: "offline-snapshot",
    replacementMode: "control-plane-portable",
    fallback: "Committed translation snapshots in messages/tolgee are the runtime fallback.",
    productionPolicy: "Production rendering consumes committed catalogs and does not require a live Tolgee network call.",
    secretEnvironmentVariables: ["TOLGEE_API_KEY"],
    publicEnvironmentVariables: [],
  },
  {
    id: "turnstile",
    capabilities: ["auth_abuse_protection"],
    category: "client-assisted",
    criticality: "important",
    serverAuthorityRequired: false,
    clientExposure: "public-widget",
    failureMode: "fail-closed",
    replacementMode: "runtime-adapter",
    fallback: "No silent production bypass. Authentication challenge fails closed until an approved anti-abuse provider/policy is available.",
    productionPolicy: "Only the public site key/widget is browser-visible; verification secret is managed by the auth authority, never by client code.",
    secretEnvironmentVariables: [],
    publicEnvironmentVariables: ["NEXT_PUBLIC_TURNSTILE_SITE_KEY"],
  },
  {
    id: "elmah",
    capabilities: ["error_observability", "uptime", "heartbeat"],
    category: "replaceable-runtime",
    criticality: "optional",
    serverAuthorityRequired: true,
    clientExposure: "none",
    failureMode: "fail-open",
    replacementMode: "runtime-adapter",
    fallback: "Structured KLYX server logs remain available when remote telemetry delivery fails.",
    productionPolicy: "Observability failure must never fail a booking, payment, account mutation or page response.",
    secretEnvironmentVariables: ["ELMAH_IO_API_KEY", "ELMAH_IO_HEARTBEAT_ID"],
    publicEnvironmentVariables: [],
  },
  {
    id: "vercel",
    capabilities: ["hosting", "deployments", "runtime", "cron"],
    category: "infrastructure",
    criticality: "critical",
    serverAuthorityRequired: true,
    clientExposure: "none",
    failureMode: "fail-closed",
    replacementMode: "planned-infrastructure-migration",
    fallback: "Portable Next.js build plus documented deployment gate; alternate hosting requires a controlled migration, not an automatic runtime switch.",
    productionPolicy: "Deployment metadata is a fence, never financial authority. Production SHA must match KLYX certification gates where required.",
    secretEnvironmentVariables: ["VERCEL_AUTOMATION_BYPASS_SECRET"],
    publicEnvironmentVariables: [],
  },
  {
    id: "github",
    capabilities: ["source_control", "ci", "branch_protection", "release_provenance"],
    category: "control-plane",
    criticality: "important",
    serverAuthorityRequired: true,
    clientExposure: "none",
    failureMode: "fail-closed",
    replacementMode: "control-plane-portable",
    fallback: "Git history can be mirrored to another remote; a GitHub outage blocks delivery/control-plane changes but not the already-running KLYX runtime.",
    productionPolicy: "Protected main and certified CI establish provenance; GitHub never authorizes runtime financial mutations by itself.",
    secretEnvironmentVariables: ["GITHUB_TOKEN"],
    publicEnvironmentVariables: [],
  },
] as const;

const providerCatalogById = new Map<KlyxProviderId, KlyxProviderDescriptor>(
  KLYX_PROVIDER_CATALOG.map((provider) => [provider.id, provider])
);

export function getKlyxProviderDescriptor(
  id: KlyxProviderId
): KlyxProviderDescriptor {
  const descriptor = providerCatalogById.get(id);

  if (!descriptor) {
    throw new Error(`Unknown KLYX provider: ${id}`);
  }

  return descriptor;
}
