import type {
  KlyxExternalProviderName,
  KlyxProviderPolicy,
} from "./contracts";

export const KLYX_PROVIDER_CATALOG = {
  openai: {
    name: "openai",
    capabilities: ["llm", "vision"],
    runtimeRole: "runtime",
    clientPolicy: "server_only",
    failurePolicy: "degrade",
    criticality: "important",
    abstractionState: "native_adapter",
    secretEnv: ["OPENAI_API_KEY"],
    publicEnv: [],
    indispensableFor: ["assistant_generation", "optional_photo_understanding"],
    freeFallback: "deterministic KLYX fallback without external generation",
    authorityBoundary:
      "OpenAI may propose language/reasoning output; KLYX deterministic server code owns every mutation and decision authority.",
  },
  supabase: {
    name: "supabase",
    capabilities: ["database", "auth", "storage"],
    runtimeRole: "runtime",
    clientPolicy: "public_token_only",
    failurePolicy: "fail_closed",
    criticality: "critical",
    abstractionState: "governed_boundary",
    secretEnv: ["SUPABASE_SERVICE_ROLE_KEY"],
    publicEnv: [
      "NEXT_PUBLIC_SUPABASE_URL",
      "NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY",
      "NEXT_PUBLIC_SUPABASE_ANON_KEY",
    ],
    indispensableFor: ["canonical_persistence", "authentication", "storage"],
    freeFallback: "local adapters/mocks only; never a production authority fallback",
    authorityBoundary:
      "Browser Auth may use publishable credentials, but privileged reads/writes and business authority remain server-side and RLS constrained.",
  },
  stripe: {
    name: "stripe",
    capabilities: ["payments", "connect", "refunds", "transfers"],
    runtimeRole: "runtime",
    clientPolicy: "public_token_only",
    failurePolicy: "fail_closed",
    criticality: "critical",
    abstractionState: "governed_boundary",
    secretEnv: ["STRIPE_SECRET_KEY", "STRIPE_WEBHOOK_SECRET"],
    publicEnv: ["NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY"],
    indispensableFor: ["external_payment_rail"],
    freeFallback: "TEST/mocks only; no production money fallback",
    authorityBoundary:
      "Stripe is an external payment rail, never KLYX financial truth. Ledger, eligibility, LIVE authorization and settlement authority remain KLYX-owned.",
  },
  sumsub: {
    name: "sumsub",
    capabilities: ["identity_verification", "kyc_kyb_evidence"],
    runtimeRole: "runtime",
    clientPolicy: "public_session_only",
    failurePolicy: "fail_closed",
    criticality: "critical",
    abstractionState: "governed_boundary",
    secretEnv: [
      "SUMSUB_APP_TOKEN",
      "SUMSUB_SECRET_KEY",
      "SUMSUB_WEBHOOK_SECRET",
    ],
    publicEnv: [],
    indispensableFor: ["external_identity_evidence_when_required"],
    freeFallback: "human review can collect evidence, but eligibility stays blocked until proof exists",
    authorityBoundary:
      "The browser may run a short-lived SDK session minted by KLYX; webhook evidence is verified server-side and KLYX economic eligibility remains authoritative.",
  },
  twilio: {
    name: "twilio",
    capabilities: ["phone_otp"],
    runtimeRole: "runtime",
    clientPolicy: "server_only",
    failurePolicy: "fail_closed",
    criticality: "important",
    abstractionState: "governed_boundary",
    secretEnv: [
      "TWILIO_API_KEY_SECRET",
      "TWILIO_AUTH_TOKEN",
      "TWILIO_ACCOUNT_SID",
      "TWILIO_VERIFY_SERVICE_SID",
    ],
    publicEnv: [],
    indispensableFor: ["phone_verification_when_required"],
    freeFallback: "email/manual verification only when policy explicitly permits it",
    authorityBoundary:
      "Twilio transports OTP challenges; KLYX server rate limits and verification policy decide whether phone proof is required and accepted.",
  },
  resend: {
    name: "resend",
    capabilities: ["transactional_email"],
    runtimeRole: "runtime",
    clientPolicy: "server_only",
    failurePolicy: "degrade",
    criticality: "important",
    abstractionState: "governed_boundary",
    secretEnv: ["RESEND_API_KEY"],
    publicEnv: [],
    indispensableFor: ["transactional_notifications"],
    freeFallback: "durable in-app notification/outbox where the workflow permits delayed email",
    authorityBoundary:
      "Resend delivers notifications only; email delivery must never become financial, booking, identity or settlement truth.",
  },
  tolgee: {
    name: "tolgee",
    capabilities: ["translation_management"],
    runtimeRole: "build_time",
    clientPolicy: "static_snapshot_only",
    failurePolicy: "degrade",
    criticality: "optional",
    abstractionState: "static_snapshot",
    secretEnv: ["TOLGEE_API_KEY"],
    publicEnv: [],
    indispensableFor: ["translation_authoring_sync"],
    freeFallback: "committed message catalogs remain the runtime source",
    authorityBoundary:
      "Tolgee manages translation content outside runtime; committed KLYX catalogs serve users when Tolgee is unavailable.",
  },
  cloudflare_turnstile: {
    name: "cloudflare_turnstile",
    capabilities: ["bot_challenge"],
    runtimeRole: "runtime",
    clientPolicy: "public_token_only",
    failurePolicy: "fail_closed",
    criticality: "important",
    abstractionState: "governed_boundary",
    secretEnv: ["TURNSTILE_SECRET_KEY"],
    publicEnv: ["NEXT_PUBLIC_TURNSTILE_SITE_KEY"],
    indispensableFor: ["public_auth_abuse_protection"],
    freeFallback: "server rate limits only as a deliberately approved degraded policy; never silent CAPTCHA bypass",
    authorityBoundary:
      "The browser may render a public challenge; only a trusted server/auth authority may accept the resulting proof.",
  },
  elmah_io: {
    name: "elmah_io",
    capabilities: ["error_reporting", "uptime", "heartbeat"],
    runtimeRole: "runtime",
    clientPolicy: "server_only",
    failurePolicy: "fail_open",
    criticality: "optional",
    abstractionState: "governed_boundary",
    secretEnv: ["ELMAH_IO_API_KEY"],
    publicEnv: [],
    indispensableFor: ["production_observability"],
    freeFallback: "Vercel/runtime logs and KLYX internal operations telemetry",
    authorityBoundary:
      "Observability is non-authoritative. Failure to report telemetry must never block a user or financial workflow.",
  },
  vercel: {
    name: "vercel",
    capabilities: ["hosting", "deployment", "runtime_logs"],
    runtimeRole: "control_plane",
    clientPolicy: "control_plane_only",
    failurePolicy: "stop_control_plane",
    criticality: "control_plane",
    abstractionState: "control_plane",
    secretEnv: ["VERCEL_TOKEN"],
    publicEnv: [],
    indispensableFor: ["current_production_hosting"],
    freeFallback: "build artifacts remain portable; migration to another host requires an explicit deployment adapter",
    authorityBoundary:
      "Vercel deploys KLYX but never owns product, financial, identity or settlement decisions.",
  },
  github: {
    name: "github",
    capabilities: ["source_control", "ci", "release_gates"],
    runtimeRole: "control_plane",
    clientPolicy: "control_plane_only",
    failurePolicy: "stop_control_plane",
    criticality: "control_plane",
    abstractionState: "control_plane",
    secretEnv: ["GITHUB_TOKEN"],
    publicEnv: [],
    indispensableFor: ["current_source_and_ci_control_plane"],
    freeFallback: "local Git mirror/export; release mutations stop until a trusted control plane is available",
    authorityBoundary:
      "GitHub can gate releases but is not runtime business authority. Protected CI evidence must remain reproducible outside GitHub.",
  },
} satisfies Record<KlyxExternalProviderName, KlyxProviderPolicy>;

export function getKlyxProviderPolicy(
  name: KlyxExternalProviderName
): KlyxProviderPolicy {
  return KLYX_PROVIDER_CATALOG[name];
}
