import type { KlyxLocale } from "@/lib/klyx-i18n";

export const KLYX_PROVIDER_JOBS_TRANSLATED_LOCALES = ["fr", "en", "nl", "de"] as const;
export type KlyxProviderJobsLocale = (typeof KLYX_PROVIDER_JOBS_TRANSLATED_LOCALES)[number];

export const KLYX_PROVIDER_JOBS_MESSAGE_KEYS = ["eyebrow","title","description","missions","multiSlot","offersSent","offerTracking","offerTrackingTitle","pending","pendingDetail","accepted","acceptedDetail","rejected","rejectedDetail","offer","offerNotBookingPayment","priority","priorityTitle","priorityDescription","bestMatch","highestBudget","clientBudgetDetail","noBudget","priceToPropose","nextAction","offerToPrepare","offerToPrepareDetail","allHandled","allHandledDetail","decisionAid","noCompatible","noCompatibleDetail","fallbackService","available","budgetTotal","clientBudget","totalSuffix","fullMissionCoverage","fullMissionCoverageDetail","slot","schedule","duration","date","time","needHelp","prepareWithKlyx","assistantControlNote","totalPrice","yourPrice","clientMessage","multiMessagePlaceholder","singleMessagePlaceholder","updateOffer","proposeAll","sendOffer","currentOffer","notSpecified","durationToConfirm","loadError","coverageError","amountError","offerError","offerSent","multiOfferSent"] as const;
export type KlyxProviderJobsMessageKey = (typeof KLYX_PROVIDER_JOBS_MESSAGE_KEYS)[number];
type Dictionary = Record<KlyxProviderJobsMessageKey, string>;

const DICTIONARIES: Record<KlyxProviderJobsLocale, Dictionary> = {
  fr: {eyebrow:"Opportunités KLYX",title:"Missions recommandées",description:"Tous les créneaux doivent être couverts. Une offre = mission complète.",missions:"Missions",multiSlot:"Multi-créneaux",offersSent:"Offres envoyées",offerTracking:"Suivi de mes offres",offerTrackingTitle:"Où en sont mes propositions ?",pending:"En attente",pendingDetail:"réponse client attendue",accepted:"Acceptée",acceptedDetail:"proposition choisie par le client",rejected:"Refusée",rejectedDetail:"aucune action nécessaire",offer:"Offre",offerNotBookingPayment:"Offre ≠ réservation ou paiement.",priority:"Priorité KLYX",priorityTitle:"Les opportunités à regarder en premier",priorityDescription:"Missions compatibles et offres envoyées.",bestMatch:"Meilleur match",highestBudget:"Budget le plus élevé",clientBudgetDetail:"Budget indiqué par le client",noBudget:"Aucun budget indiqué",priceToPropose:"Le prix reste à proposer.",nextAction:"Prochaine action",offerToPrepare:"Offre à préparer",offerToPrepareDetail:"Cette mission compatible n’a encore reçu aucune offre de ta part.",allHandled:"Tout est traité",allHandledDetail:"Tu as déjà envoyé une offre sur toutes les opportunités actuellement affichées.",decisionAid:"Cette priorité est une aide à la décision. Tu fixes toi-même ton prix et tu confirmes chaque offre avant son envoi.",noCompatible:"Aucune mission compatible",noCompatibleDetail:"Pour une mission multi-créneaux, KLYX attend que tu sois disponible sur tous les créneaux avant de te la proposer.",fallbackService:"Service KLYX",available:"disponible",budgetTotal:"Budget total",clientBudget:"Budget client",totalSuffix:"au total",fullMissionCoverage:"Tu couvres toute la mission",fullMissionCoverageDetail:"Ton offre sera un prix unique pour tous les créneaux.",slot:"Créneau",schedule:"Horaire",duration:"Durée",date:"Date",time:"Heure",needHelp:"Besoin d’aide pour répondre ?",prepareWithKlyx:"Préparer avec KLYX",assistantControlNote:"L’assistant prépare uniquement le contexte. Le prix final et l’envoi de l’offre restent sous ton contrôle.",totalPrice:"Ton prix total",yourPrice:"Ton prix",clientMessage:"Message au client",multiMessagePlaceholder:"Confirme que ton prix couvre tous les créneaux.",singleMessagePlaceholder:"Explique pourquoi tu corresponds à cette mission.",updateOffer:"Mettre à jour",proposeAll:"Proposer pour tout",sendOffer:"Envoyer l’offre",currentOffer:"Offre actuelle",notSpecified:"Non précisé",durationToConfirm:"Durée à confirmer",loadError:"Impossible de charger les missions pour le moment.",coverageError:"Cette mission exige une couverture complète de tous les créneaux.",amountError:"Entre un montant supérieur à 0.",offerError:"Impossible d’envoyer l’offre pour le moment.",offerSent:"Offre envoyée.",multiOfferSent:"Offre totale envoyée pour tous les créneaux."},
  en: {eyebrow:"KLYX opportunities",title:"Recommended jobs",description:"Every time slot must be covered. One offer = the complete job.",missions:"Jobs",multiSlot:"Multi-slot",offersSent:"Offers sent",offerTracking:"My offer tracking",offerTrackingTitle:"Where do my proposals stand?",pending:"Pending",pendingDetail:"waiting for the client",accepted:"Accepted",acceptedDetail:"proposal selected by the client",rejected:"Rejected",rejectedDetail:"no action required",offer:"Offer",offerNotBookingPayment:"An offer is not a booking or a payment.",priority:"KLYX priority",priorityTitle:"Opportunities to review first",priorityDescription:"Compatible jobs and offers already sent.",bestMatch:"Best match",highestBudget:"Highest budget",clientBudgetDetail:"Budget provided by the client",noBudget:"No budget provided",priceToPropose:"You still need to propose a price.",nextAction:"Next action",offerToPrepare:"Offer to prepare",offerToPrepareDetail:"You have not sent an offer for this compatible job yet.",allHandled:"Everything is handled",allHandledDetail:"You have already sent an offer for every opportunity currently shown.",decisionAid:"This priority is decision support only. You set your own price and confirm every offer before it is sent.",noCompatible:"No compatible jobs",noCompatibleDetail:"For a multi-slot job, KLYX only shows it once you are available for every slot.",fallbackService:"KLYX service",available:"available",budgetTotal:"Total budget",clientBudget:"Client budget",totalSuffix:"total",fullMissionCoverage:"You cover the complete job",fullMissionCoverageDetail:"Your offer will be one price for all time slots.",slot:"Slot",schedule:"Schedule",duration:"Duration",date:"Date",time:"Time",needHelp:"Need help preparing a reply?",prepareWithKlyx:"Prepare with KLYX",assistantControlNote:"The assistant only prepares context. The final price and sending the offer remain under your control.",totalPrice:"Your total price",yourPrice:"Your price",clientMessage:"Message to the client",multiMessagePlaceholder:"Confirm that your price covers every time slot.",singleMessagePlaceholder:"Explain why you are a good fit for this job.",updateOffer:"Update offer",proposeAll:"Offer for all slots",sendOffer:"Send offer",currentOffer:"Current offer",notSpecified:"Not specified",durationToConfirm:"Duration to confirm",loadError:"KLYX cannot load provider jobs right now.",coverageError:"This job requires full coverage of every time slot.",amountError:"Enter an amount greater than 0.",offerError:"KLYX cannot send this offer right now.",offerSent:"Offer sent.",multiOfferSent:"Total offer sent for every time slot."},
  nl: {eyebrow:"KLYX-opportuniteiten",title:"Aanbevolen opdrachten",description:"Alle tijdsloten moeten gedekt zijn. Eén aanbod = de volledige opdracht.",missions:"Opdrachten",multiSlot:"Meerdere tijdsloten",offersSent:"Verzonden aanbiedingen",offerTracking:"Mijn aanbiedingen volgen",offerTrackingTitle:"Wat is de status van mijn voorstellen?",pending:"In afwachting",pendingDetail:"wachten op de klant",accepted:"Geaccepteerd",acceptedDetail:"voorstel gekozen door de klant",rejected:"Afgewezen",rejectedDetail:"geen actie nodig",offer:"Aanbod",offerNotBookingPayment:"Een aanbod is geen boeking of betaling.",priority:"KLYX-prioriteit",priorityTitle:"Opportuniteiten om eerst te bekijken",priorityDescription:"Compatibele opdrachten en verzonden aanbiedingen.",bestMatch:"Beste match",highestBudget:"Hoogste budget",clientBudgetDetail:"Budget opgegeven door de klant",noBudget:"Geen budget opgegeven",priceToPropose:"Je moet nog een prijs voorstellen.",nextAction:"Volgende actie",offerToPrepare:"Aanbod voorbereiden",offerToPrepareDetail:"Je hebt voor deze compatibele opdracht nog geen aanbod verstuurd.",allHandled:"Alles is behandeld",allHandledDetail:"Je hebt al een aanbod verstuurd voor alle momenteel getoonde opportuniteiten.",decisionAid:"Deze prioriteit is alleen beslissingsondersteuning. Jij bepaalt je prijs en bevestigt elk aanbod voordat het wordt verzonden.",noCompatible:"Geen compatibele opdrachten",noCompatibleDetail:"Bij een opdracht met meerdere tijdsloten toont KLYX die pas wanneer je voor alle tijdsloten beschikbaar bent.",fallbackService:"KLYX-dienst",available:"beschikbaar",budgetTotal:"Totaalbudget",clientBudget:"Klantbudget",totalSuffix:"totaal",fullMissionCoverage:"Je dekt de volledige opdracht",fullMissionCoverageDetail:"Je aanbod is één prijs voor alle tijdsloten.",slot:"Tijdslot",schedule:"Uurrooster",duration:"Duur",date:"Datum",time:"Tijd",needHelp:"Hulp nodig om te antwoorden?",prepareWithKlyx:"Voorbereiden met KLYX",assistantControlNote:"De assistent bereidt alleen de context voor. De uiteindelijke prijs en het verzenden van het aanbod blijven onder jouw controle.",totalPrice:"Je totaalprijs",yourPrice:"Je prijs",clientMessage:"Bericht aan de klant",multiMessagePlaceholder:"Bevestig dat je prijs alle tijdsloten dekt.",singleMessagePlaceholder:"Leg uit waarom je bij deze opdracht past.",updateOffer:"Aanbod bijwerken",proposeAll:"Aanbod voor alles",sendOffer:"Aanbod verzenden",currentOffer:"Huidig aanbod",notSpecified:"Niet opgegeven",durationToConfirm:"Duur te bevestigen",loadError:"KLYX kan de opdrachten momenteel niet laden.",coverageError:"Deze opdracht vereist volledige dekking van alle tijdsloten.",amountError:"Voer een bedrag groter dan 0 in.",offerError:"KLYX kan dit aanbod momenteel niet verzenden.",offerSent:"Aanbod verzonden.",multiOfferSent:"Totaalaanbod voor alle tijdsloten verzonden."},
  de: {eyebrow:"KLYX-Chancen",title:"Empfohlene Aufträge",description:"Alle Zeitfenster müssen abgedeckt sein. Ein Angebot = der vollständige Auftrag.",missions:"Aufträge",multiSlot:"Mehrere Zeitfenster",offersSent:"Gesendete Angebote",offerTracking:"Meine Angebote verfolgen",offerTrackingTitle:"Wie ist der Stand meiner Angebote?",pending:"Ausstehend",pendingDetail:"Antwort des Kunden ausstehend",accepted:"Angenommen",acceptedDetail:"vom Kunden ausgewähltes Angebot",rejected:"Abgelehnt",rejectedDetail:"keine Aktion erforderlich",offer:"Angebot",offerNotBookingPayment:"Ein Angebot ist weder Buchung noch Zahlung.",priority:"KLYX-Priorität",priorityTitle:"Chancen, die du zuerst prüfen solltest",priorityDescription:"Passende Aufträge und bereits gesendete Angebote.",bestMatch:"Beste Übereinstimmung",highestBudget:"Höchstes Budget",clientBudgetDetail:"Vom Kunden angegebenes Budget",noBudget:"Kein Budget angegeben",priceToPropose:"Du musst noch einen Preis vorschlagen.",nextAction:"Nächste Aktion",offerToPrepare:"Angebot vorbereiten",offerToPrepareDetail:"Für diesen passenden Auftrag hast du noch kein Angebot gesendet.",allHandled:"Alles erledigt",allHandledDetail:"Du hast für alle aktuell angezeigten Chancen bereits ein Angebot gesendet.",decisionAid:"Diese Priorität ist nur eine Entscheidungshilfe. Du legst deinen Preis selbst fest und bestätigst jedes Angebot vor dem Senden.",noCompatible:"Keine passenden Aufträge",noCompatibleDetail:"Bei einem Auftrag mit mehreren Zeitfenstern zeigt KLYX ihn erst, wenn du für alle Zeitfenster verfügbar bist.",fallbackService:"KLYX-Dienst",available:"verfügbar",budgetTotal:"Gesamtbudget",clientBudget:"Kundenbudget",totalSuffix:"insgesamt",fullMissionCoverage:"Du deckst den vollständigen Auftrag ab",fullMissionCoverageDetail:"Dein Angebot ist ein Preis für alle Zeitfenster.",slot:"Zeitfenster",schedule:"Uhrzeit",duration:"Dauer",date:"Datum",time:"Zeit",needHelp:"Brauchst du Hilfe bei der Antwort?",prepareWithKlyx:"Mit KLYX vorbereiten",assistantControlNote:"Der Assistent bereitet nur den Kontext vor. Endpreis und Versand des Angebots bleiben unter deiner Kontrolle.",totalPrice:"Dein Gesamtpreis",yourPrice:"Dein Preis",clientMessage:"Nachricht an den Kunden",multiMessagePlaceholder:"Bestätige, dass dein Preis alle Zeitfenster abdeckt.",singleMessagePlaceholder:"Erkläre, warum du zu diesem Auftrag passt.",updateOffer:"Angebot aktualisieren",proposeAll:"Für alles anbieten",sendOffer:"Angebot senden",currentOffer:"Aktuelles Angebot",notSpecified:"Nicht angegeben",durationToConfirm:"Dauer zu bestätigen",loadError:"KLYX kann die Aufträge derzeit nicht laden.",coverageError:"Dieser Auftrag erfordert vollständige Abdeckung aller Zeitfenster.",amountError:"Gib einen Betrag größer als 0 ein.",offerError:"KLYX kann dieses Angebot derzeit nicht senden.",offerSent:"Angebot gesendet.",multiOfferSent:"Gesamtangebot für alle Zeitfenster gesendet."},
};

const INTL_LOCALES: Record<KlyxProviderJobsLocale, string> = {fr:"fr-BE",en:"en-BE",nl:"nl-BE",de:"de-BE"};
const STATUS_LABELS: Record<KlyxProviderJobsLocale, Record<string,string>> = {
  fr:{pending:"En attente",sent:"En attente",accepted:"Acceptée",rejected:"Refusée"},
  en:{pending:"Pending",sent:"Pending",accepted:"Accepted",rejected:"Rejected"},
  nl:{pending:"In afwachting",sent:"In afwachting",accepted:"Geaccepteerd",rejected:"Afgewezen"},
  de:{pending:"Ausstehend",sent:"Ausstehend",accepted:"Angenommen",rejected:"Abgelehnt"},
};

export function resolveKlyxProviderJobsLocale(locale: KlyxLocale | string): KlyxProviderJobsLocale { return KLYX_PROVIDER_JOBS_TRANSLATED_LOCALES.includes(locale as KlyxProviderJobsLocale) ? locale as KlyxProviderJobsLocale : "fr"; }
export function getKlyxProviderJobsDictionary(locale: KlyxLocale | string): Dictionary { return DICTIONARIES[resolveKlyxProviderJobsLocale(locale)]; }
export function translateKlyxProviderJobs(locale: KlyxLocale | string,key: KlyxProviderJobsMessageKey): string { return getKlyxProviderJobsDictionary(locale)[key]; }
export function translateKlyxProviderJobOfferStatus(locale: KlyxLocale | string,status: string): string { const r=resolveKlyxProviderJobsLocale(locale); return STATUS_LABELS[r][status] ?? status; }
export function getKlyxProviderJobsIntlLocale(locale: KlyxLocale | string): string { return INTL_LOCALES[resolveKlyxProviderJobsLocale(locale)]; }
export function formatKlyxProviderJobsMoney(locale: KlyxLocale | string,value: number | null,currency: string): string { if(value===null)return translateKlyxProviderJobs(locale,"notSpecified"); const code=currency?.trim().toUpperCase(); if(!/^[A-Z]{3}$/.test(code))return value.toFixed(2); return new Intl.NumberFormat(getKlyxProviderJobsIntlLocale(locale),{style:"currency",currency:code}).format(value); }
export function formatKlyxProviderJobsDate(locale: KlyxLocale | string,value: string): string { return new Intl.DateTimeFormat(getKlyxProviderJobsIntlLocale(locale),{weekday:"short",day:"2-digit",month:"short",year:"numeric"}).format(new Date(`${value}T12:00:00`)); }
export function formatKlyxProviderJobsDuration(locale: KlyxLocale | string,minutes: number | null): string { if(minutes===null||minutes<=0)return translateKlyxProviderJobs(locale,"durationToConfirm"); const h=Math.floor(minutes/60),r=minutes%60; if(h>0&&r>0)return `${h} h ${r} min`; if(h>0)return `${h} h`; return `${r} min`; }
export function translateKlyxProviderJobsMatch(locale: KlyxLocale | string,score: number): string { const r=resolveKlyxProviderJobsLocale(locale); const b=score>=90?0:score>=80?1:score>=70?2:score>=60?3:4; const labels:Record<KlyxProviderJobsLocale,readonly string[]>={fr:["Excellent match","Très bon match","Bon match","Compatible","À étudier"],en:["Excellent match","Very good match","Good match","Compatible","Review"],nl:["Uitstekende match","Zeer goede match","Goede match","Compatibel","Te bekijken"],de:["Ausgezeichnete Übereinstimmung","Sehr gute Übereinstimmung","Gute Übereinstimmung","Kompatibel","Prüfen"]}; return labels[r][b]; }
export function formatKlyxProviderJobsCount(locale: KlyxLocale | string,count: number,kind:"mission"|"offer"|"slot"): string { const r=resolveKlyxProviderJobsLocale(locale); if(kind==="offer"){if(r==="en")return `${count} offer${count===1?"":"s"} sent`;if(r==="nl")return `${count} aanbod${count===1?"":"en"} verzonden`;if(r==="de")return `${count} ${count===1?"Angebot":"Angebote"} gesendet`;return `${count} offre${count===1?"":"s"} envoyée${count===1?"":"s"}`;} if(kind==="slot"){if(r==="en")return `${count} slot${count===1?"":"s"}`;if(r==="nl")return `${count} tijdslot${count===1?"":"en"}`;if(r==="de")return `${count} Zeitfenster`;return `${count} créneau${count===1?"":"x"}`;} if(r==="en")return `${count} job${count===1?"":"s"} available`;if(r==="nl")return `${count} opdracht${count===1?"":"en"} beschikbaar`;if(r==="de")return `${count} ${count===1?"Auftrag":"Aufträge"} verfügbar`;return `${count} mission${count===1?"":"s"} disponible${count===1?"":"s"}`; }
