$ErrorActionPreference = "Stop"

$root = Split-Path -Parent $PSScriptRoot
$utf8 = New-Object System.Text.UTF8Encoding($false)

function Decode([string]$Value) {
    return [System.Text.Encoding]::UTF8.GetString([Convert]::FromBase64String($Value))
}

$block = Decode "Ci8vIEtMWVhfQ0FOT05JQ0FMX0ZJTkFOQ0VfVFJBTlNBQ1RJT05TXzEzXzExCgogICAgdHlwZSBDb21tZXJjaWFsVHJhbnNhY3Rpb24xM18xMSA9CiAgICAgICh0eXBlb2YgcmF3VHJhbnNhY3Rpb25zMTNfMTEpW251bWJlcl07CgogICAgY29uc3QgY29tbWVyY2lhbEJ1Y2tldHMxM18xMSA9CiAgICAgIG5ldyBNYXA8CiAgICAgICAgc3RyaW5nLAogICAgICAgIENvbW1lcmNpYWxUcmFuc2FjdGlvbjEzXzExW10KICAgICAgPigpOwoKICAgIGNvbnN0IGNvbW1lcmNpYWxTaW5nbGVzMTNfMTE6CiAgICAgIENvbW1lcmNpYWxUcmFuc2FjdGlvbjEzXzExW10gPQogICAgICBbXTsKCiAgICBmb3IgKAogICAgICBjb25zdCB0cmFuc2FjdGlvbgogICAgICBvZiByYXdUcmFuc2FjdGlvbnMxM18xMQogICAgKSB7CiAgICAgIGlmICgKICAgICAgICAhdHJhbnNhY3Rpb24uYm9va2luZ0dyb3VwSWQKICAgICAgKSB7CiAgICAgICAgY29tbWVyY2lhbFNpbmdsZXMxM18xMS5wdXNoKAogICAgICAgICAgdHJhbnNhY3Rpb24KICAgICAgICApOwoKICAgICAgICBjb250aW51ZTsKICAgICAgfQoKICAgICAgLyoKICAgICAgICBmaW5hbmNpYWxFdmVudEtleSBlc3QgZGVqYSBncm91cC1hd2FyZQogICAgICAgIGRlcHVpcyAxMy4wNCA6CgogICAgICAgIGdyb3VwOjxncm91cElkPjo8ZW50cnlUeXBlPjo8c3RyaXBlRXZlbnQ+CgogICAgICAgIExlcyBhbGxvY2F0aW9ucyBlbmZhbnRzIGFwcGFydGVuYW50IGF1CiAgICAgICAgbWVtZSBldmVuZW1lbnQgY29tbWVyY2lhbCB0b21iZW50IGRvbmMKICAgICAgICBkYW5zIGxlIG1lbWUgYnVja2V0LgogICAgICAqLwogICAgICBjb25zdCBrZXkgPQogICAgICAgIHRyYW5zYWN0aW9uLmZpbmFuY2lhbEV2ZW50S2V5OwoKICAgICAgY29uc3QgY3VycmVudCA9CiAgICAgICAgY29tbWVyY2lhbEJ1Y2tldHMxM18xMS5nZXQoCiAgICAgICAgICBrZXkKICAgICAgICApID8/CiAgICAgICAgW107CgogICAgICBjdXJyZW50LnB1c2goCiAgICAgICAgdHJhbnNhY3Rpb24KICAgICAgKTsKCiAgICAgIGNvbW1lcmNpYWxCdWNrZXRzMTNfMTEuc2V0KAogICAgICAgIGtleSwKICAgICAgICBjdXJyZW50CiAgICAgICk7CiAgICB9CgogICAgY29uc3QgY29tbWVyY2lhbEdyb3VwczEzXzExOgogICAgICBDb21tZXJjaWFsVHJhbnNhY3Rpb24xM18xMVtdID0KICAgICAgW107CgogICAgZm9yICgKICAgICAgY29uc3QgWwogICAgICAgIGV2ZW50S2V5LAogICAgICAgIHJvd3MKICAgICAgXQogICAgICBvZiBjb21tZXJjaWFsQnVja2V0czEzXzExCiAgICApIHsKICAgICAgY29uc3QgZmlyc3QgPQogICAgICAgIHJvd3NbMF07CgogICAgICBpZiAoIWZpcnN0KSB7CiAgICAgICAgY29udGludWU7CiAgICAgIH0KCiAgICAgIGNvbnN0IGdyb3VwSWQgPQogICAgICAgIGZpcnN0LmJvb2tpbmdHcm91cElkOwoKICAgICAgaWYgKCFncm91cElkKSB7CiAgICAgICAgY29udGludWU7CiAgICAgIH0KCiAgICAgIGNvbnN0IGdyb3VwID0KICAgICAgICBncm91cEJ5SWQuZ2V0KAogICAgICAgICAgZ3JvdXBJZAogICAgICAgICk7CgogICAgICBjb25zdCBjYW5vbmljYWwgPQogICAgICAgIGdyb3VwCiAgICAgICAgICA/IGNhbm9uaWNhbEdyb3VwVG90YWwoCiAgICAgICAgICAgICAgZ3JvdXAKICAgICAgICAgICAgKQogICAgICAgICAgOiBudWxsOwoKICAgICAgY29uc3QgcmF3R3Jvc3MgPQogICAgICAgIHJvd3MucmVkdWNlKAogICAgICAgICAgKAogICAgICAgICAgICB0b3RhbCwKICAgICAgICAgICAgcm93CiAgICAgICAgICApID0+CiAgICAgICAgICAgIHRvdGFsICsKICAgICAgICAgICAgY2VudHMoCiAgICAgICAgICAgICAgcm93Lmdyb3NzQW1vdW50Q2VudHMKICAgICAgICAgICAgKSwKICAgICAgICAgIDAKICAgICAgICApOwoKICAgICAgY29uc3QgcmF3RmVlID0KICAgICAgICByb3dzLnJlZHVjZSgKICAgICAgICAgICgKICAgICAgICAgICAgdG90YWwsCiAgICAgICAgICAgIHJvdwogICAgICAgICAgKSA9PgogICAgICAgICAgICB0b3RhbCArCiAgICAgICAgICAgIGNlbnRzKAogICAgICAgICAgICAgIHJvdy5wbGF0Zm9ybUZlZUNlbnRzCiAgICAgICAgICAgICksCiAgICAgICAgICAwCiAgICAgICAgKTsKCiAgICAgIGNvbnN0IHJhd1Byb3ZpZGVyID0KICAgICAgICByb3dzLnJlZHVjZSgKICAgICAgICAgICgKICAgICAgICAgICAgdG90YWwsCiAgICAgICAgICAgIHJvdwogICAgICAgICAgKSA9PgogICAgICAgICAgICB0b3RhbCArCiAgICAgICAgICAgIGNlbnRzKAogICAgICAgICAgICAgIHJvdy5wcm92aWRlckFtb3VudENlbnRzCiAgICAgICAgICAgICksCiAgICAgICAgICAwCiAgICAgICAgKTsKCiAgICAgIGNvbnN0IHJhd1JlZnVuZCA9CiAgICAgICAgcm93cy5yZWR1Y2UoCiAgICAgICAgICAoCiAgICAgICAgICAgIHRvdGFsLAogICAgICAgICAgICByb3cKICAgICAgICAgICkgPT4KICAgICAgICAgICAgdG90YWwgKwogICAgICAgICAgICBjZW50cygKICAgICAgICAgICAgICByb3cucmVmdW5kQW1vdW50Q2VudHMKICAgICAgICAgICAgKSwKICAgICAgICAgIDAKICAgICAgICApOwoKICAgICAgbGV0IGdyb3NzQW1vdW50Q2VudHMgPQogICAgICAgIHJhd0dyb3NzOwoKICAgICAgbGV0IHBsYXRmb3JtRmVlQ2VudHMgPQogICAgICAgIHJhd0ZlZTsKCiAgICAgIGxldCBwcm92aWRlckFtb3VudENlbnRzOgogICAgICAgIG51bWJlciB8IG51bGwgPQogICAgICAgIHJhd1Byb3ZpZGVyOwoKICAgICAgbGV0IHJlZnVuZEFtb3VudENlbnRzID0KICAgICAgICByYXdSZWZ1bmQ7CgogICAgICAvKgogICAgICAgIExlIHNuYXBzaG90IGdyb3VwZSByZXN0ZSBsYSBsaW1pdGUKICAgICAgICBjb21tZXJjaWFsZSBjYW5vbmlxdWUuCgogICAgICAgIEV4ZW1wbGUgbGVnaXRpbWUgOgogICAgICAgIDUwICsgNTAgPSAxMDAKICAgICAgICA9PiByZXN0ZSAxMDAuCgogICAgICAgIEV4ZW1wbGUgZHVwbGlxdWUgOgogICAgICAgIDEwMCArIDEwMCA9IDIwMAogICAgICAgIHRvdGFsIGdyb3VwZSA9IDEwMAogICAgICAgID0+IFVJIGNvbW1lcmNpYWxlID0gMTAwLgogICAgICAqLwogICAgICBpZiAoCiAgICAgICAgY2Fub25pY2FsICYmCiAgICAgICAgY2Fub25pY2FsLmNlbnRzID4KICAgICAgICAgIDAKICAgICAgKSB7CiAgICAgICAgaWYgKAogICAgICAgICAgZmlyc3QuZW50cnlUeXBlID09PQogICAgICAgICAgICAicGF5bWVudF9zdWNjZWVkZWQiICYmCiAgICAgICAgICBmaXJzdC5zdGF0dXMgPT09CiAgICAgICAgICAgICJzdWNjZWVkZWQiCiAgICAgICAgKSB7CiAgICAgICAgICBjb25zdCByYXRpbyA9CiAgICAgICAgICAgIHJhd0dyb3NzID4KICAgICAgICAgICAgICBjYW5vbmljYWwuY2VudHMgJiYKICAgICAgICAgICAgcmF3R3Jvc3MgPgogICAgICAgICAgICAgIDAKICAgICAgICAgICAgICA/IGNhbm9uaWNhbC5jZW50cyAvCiAgICAgICAgICAgICAgICByYXdHcm9zcwogICAgICAgICAgICAgIDogMTsKCiAgICAgICAgICBncm9zc0Ftb3VudENlbnRzID0KICAgICAgICAgICAgY2Fub25pY2FsLmNlbnRzOwoKICAgICAgICAgIHBsYXRmb3JtRmVlQ2VudHMgPQogICAgICAgICAgICBNYXRoLm1pbigKICAgICAgICAgICAgICBjYW5vbmljYWwuY2VudHMsCiAgICAgICAgICAgICAgTWF0aC5tYXgoCiAgICAgICAgICAgICAgICBNYXRoLnJvdW5kKAogICAgICAgICAgICAgICAgICByYXdGZWUgKgogICAgICAgICAgICAgICAgICByYXRpbwogICAgICAgICAgICAgICAgKSwKICAgICAgICAgICAgICAgIDAKICAgICAgICAgICAgICApCiAgICAgICAgICAgICk7CgogICAgICAgICAgcHJvdmlkZXJBbW91bnRDZW50cyA9CiAgICAgICAgICAgIE1hdGgubWluKAogICAgICAgICAgICAgIGNhbm9uaWNhbC5jZW50cywKICAgICAgICAgICAgICBNYXRoLm1heCgKICAgICAgICAgICAgICAgIE1hdGgucm91bmQoCiAgICAgICAgICAgICAgICAgIHJhd1Byb3ZpZGVyICoKICAgICAgICAgICAgICAgICAgcmF0aW8KICAgICAgICAgICAgICAgICksCiAgICAgICAgICAgICAgICAwCiAgICAgICAgICAgICAgKQogICAgICAgICAgICApOwoKICAgICAgICAgIGlmICgKICAgICAgICAgICAgcHJvdmlkZXJBbW91bnRDZW50cyA9PT0KICAgICAgICAgICAgICAwICYmCiAgICAgICAgICAgIHBsYXRmb3JtRmVlQ2VudHMgPgogICAgICAgICAgICAgIDAKICAgICAgICAgICkgewogICAgICAgICAgICBwcm92aWRlckFtb3VudENlbnRzID0KICAgICAgICAgICAgICBNYXRoLm1heCgKICAgICAgICAgICAgICAgIGNhbm9uaWNhbC5jZW50cyAtCiAgICAgICAgICAgICAgICAgIHBsYXRmb3JtRmVlQ2VudHMsCiAgICAgICAgICAgICAgICAwCiAgICAgICAgICAgICAgKTsKICAgICAgICAgIH0KICAgICAgICB9CiAgICAgICAgZWxzZSBpZiAoCiAgICAgICAgICBmaXJzdC5lbnRyeVR5cGUgPT09CiAgICAgICAgICAgICJyZWZ1bmRfc3VjY2VlZGVkIgogICAgICAgICkgewogICAgICAgICAgcmVmdW5kQW1vdW50Q2VudHMgPQogICAgICAgICAgICBNYXRoLm1pbigKICAgICAgICAgICAgICBjYW5vbmljYWwuY2VudHMsCiAgICAgICAgICAgICAgcmF3UmVmdW5kCiAgICAgICAgICAgICk7CgogICAgICAgICAgZ3Jvc3NBbW91bnRDZW50cyA9CiAgICAgICAgICAgIE1hdGgubWluKAogICAgICAgICAgICAgIGNhbm9uaWNhbC5jZW50cywKICAgICAgICAgICAgICByYXdHcm9zcwogICAgICAgICAgICApOwogICAgICAgIH0KICAgICAgICBlbHNlIHsKICAgICAgICAgIGdyb3NzQW1vdW50Q2VudHMgPQogICAgICAgICAgICBNYXRoLm1pbigKICAgICAgICAgICAgICBjYW5vbmljYWwuY2VudHMsCiAgICAgICAgICAgICAgcmF3R3Jvc3MKICAgICAgICAgICAgKTsKCiAgICAgICAgICByZWZ1bmRBbW91bnRDZW50cyA9CiAgICAgICAgICAgIE1hdGgubWluKAogICAgICAgICAgICAgIGNhbm9uaWNhbC5jZW50cywKICAgICAgICAgICAgICByYXdSZWZ1bmQKICAgICAgICAgICAgKTsKICAgICAgICB9CiAgICAgIH0KCiAgICAgIGNvbnN0IG5ld2VzdENyZWF0ZWRBdCA9CiAgICAgICAgcm93cwogICAgICAgICAgLm1hcCgKICAgICAgICAgICAgKHJvdykgPT4KICAgICAgICAgICAgICByb3cuY3JlYXRlZEF0CiAgICAgICAgICApCiAgICAgICAgICAuZmlsdGVyKAogICAgICAgICAgICBCb29sZWFuCiAgICAgICAgICApCiAgICAgICAgICAuc29ydCgpCiAgICAgICAgICAucmV2ZXJzZSgpWzBdID8/CiAgICAgICAgZmlyc3QuY3JlYXRlZEF0OwoKICAgICAgY29tbWVyY2lhbEdyb3VwczEzXzExLnB1c2goewogICAgICAgIC4uLmZpcnN0LAoKICAgICAgICBpZDoKICAgICAgICAgICJjb21tZXJjaWFsLSIgKwogICAgICAgICAgZ3JvdXBJZCArCiAgICAgICAgICAiLSIgKwogICAgICAgICAgZXZlbnRLZXksCgogICAgICAgIGdyb3VwZWQ6CiAgICAgICAgICB0cnVlLAoKICAgICAgICBncm9zc0Ftb3VudENlbnRzLAoKICAgICAgICBwbGF0Zm9ybUZlZUNlbnRzLAoKICAgICAgICBwcm92aWRlckFtb3VudENlbnRzLAoKICAgICAgICByZWZ1bmRBbW91bnRDZW50cywKCiAgICAgICAgY3JlYXRlZEF0OgogICAgICAgICAgbmV3ZXN0Q3JlYXRlZEF0LAoKICAgICAgICBmaW5hbmNpYWxFdmVudEtleToKICAgICAgICAgIGV2ZW50S2V5LAogICAgICB9KTsKICAgIH0KCiAgICAvKgogICAgICBJTVBPUlRBTlQgMTMuMTEKCiAgICAgIHRyYW5zYWN0aW9ucyA9CiAgICAgIHZ1ZSBjb21tZXJjaWFsZSBwcmVzdGF0YWlyZS4KCiAgICAgIExlIGxlZGdlciBicnV0IHJlc3RlIGludGFjdCBlbiBEQgogICAgICBldCByZXN0ZSBjb25zdWx0YWJsZSB2aWEgbCdhdWRpdCAxMy4wMy4KICAgICovCiAgICBjb25zdCB0cmFuc2FjdGlvbnMgPQogICAgICBbCiAgICAgICAgLi4uY29tbWVyY2lhbFNpbmdsZXMxM18xMSwKICAgICAgICAuLi5jb21tZXJjaWFsR3JvdXBzMTNfMTEsCiAgICAgIF0KICAgICAgICAuc29ydCgKICAgICAgICAgICgKICAgICAgICAgICAgZmlyc3QsCiAgICAgICAgICAgIHNlY29uZAogICAgICAgICAgKSA9PgogICAgICAgICAgICBuZXcgRGF0ZSgKICAgICAgICAgICAgICBzZWNvbmQuY3JlYXRlZEF0CiAgICAgICAgICAgICkuZ2V0VGltZSgpIC0KICAgICAgICAgICAgbmV3IERhdGUoCiAgICAgICAgICAgICAgZmlyc3QuY3JlYXRlZEF0CiAgICAgICAgICAgICkuZ2V0VGltZSgpCiAgICAgICAgKQogICAgICAgIC5zbGljZSgKICAgICAgICAgIDAsCiAgICAgICAgICAxMDAKICAgICAgICApOw=="

$financePath = Join-Path $root "app\api\provider\finance\route.ts"
$auditPath = Join-Path $root "app\api\provider\finance-audit\route.ts"
$pagePath = Join-Path $root "app\provider\payments\page.tsx"

foreach ($path in @($financePath, $auditPath, $pagePath)) {
    if (-not (Test-Path -LiteralPath $path)) {
        throw "13.11 : fichier requis introuvable : $path"
    }
}

$finance = [System.IO.File]::ReadAllText($financePath)
$audit = [System.IO.File]::ReadAllText($auditPath)
$page = [System.IO.File]::ReadAllText($pagePath)

if (-not $finance.Contains("KLYX_GROUP_SCHEMA_RUNTIME_FINANCE_13_05C")) {
    throw "13.11 : KLYX 13.05c introuvable."
}

if (-not $audit.Contains("KLYX_GROUP_FINANCE_AUDIT_API_13_03")) {
    throw "13.11 : audit financier 13.03 introuvable."
}

if (-not $page.Contains("KLYX_GROUP_FINANCE_AUDIT_PAGE_13_03")) {
    throw "13.11 : page paiements 13.03 introuvable."
}

if ($finance.Contains("KLYX_CANONICAL_FINANCE_TRANSACTIONS_13_11")) {
    Write-Host "KLYX 13.11 deja applique."
    exit 0
}

# ------------------------------------------------------------
# 1. Renomme uniquement la liste ledger brute.
# ------------------------------------------------------------

$pattern = '(?m)^\s{4}const transactions\s*='
$matches = [regex]::Matches($finance, $pattern)

if ($matches.Count -ne 1) {
    throw "13.11 : declaration transactions ambigue. Nombre trouve : $($matches.Count)"
}

$match = $matches[0]

$replacement = "    const rawTransactions13_11 ="

$finance =
    $finance.Remove(
        $match.Index,
        $match.Length
    ).Insert(
        $match.Index,
        $replacement
    )

# ------------------------------------------------------------
# 2. Insere la canonicalisation juste avant le retour final.
# ------------------------------------------------------------

$anchor = "    return NextResponse.json({"
$returnIndex = $finance.LastIndexOf($anchor)

if ($returnIndex -lt 0) {
    throw "13.11 : retour final finance introuvable."
}

$finance =
    $finance.Insert(
        $returnIndex,
        $block + "`r`n`r`n"
    )

$timestamp = Get-Date -Format "yyyyMMdd-HHmmss"

Copy-Item -LiteralPath $financePath -Destination ($financePath + ".bak-13-11-" + $timestamp) -Force

[System.IO.File]::WriteAllText($financePath, $finance, $utf8)

Write-Host ""
Write-Host "======================================"
Write-Host "KLYX 13.11 APPLIQUE"
Write-Host "======================================"
Write-Host "Transactions simples : 1 LIGNE LEDGER"
Write-Host "Mission groupee : 1 EVENEMENT COMMERCIAL"
Write-Host "Allocations enfants UI : FUSIONNEES"
Write-Host "Montant groupe : CANONIQUE"
Write-Host "Ledger DB : INCHANGE"
Write-Host "Audit 13.03 : INCHANGE"
Write-Host "Stripe : INCHANGE"
Write-Host "Migration : AUCUNE"
Write-Host "======================================"
