$ErrorActionPreference = "Stop"

$projectRoot = Split-Path -Parent $PSScriptRoot

$apiPath = Join-Path `
    $projectRoot `
    "app\api\brain\actions\route.ts"

$pagePath = Join-Path `
    $projectRoot `
    "app\assistant\actions\page.tsx"

Write-Host ""
Write-Host "KLYX 12.78 - Brain Mission Lifecycle"
Write-Host ""

foreach ($path in @(
    $apiPath,
    $pagePath
)) {
    if (-not (Test-Path -LiteralPath $path)) {
        throw "Fichier introuvable : $path"
    }
}

$utf8NoBom =
    New-Object System.Text.UTF8Encoding($false)

# ============================================================
# BRAIN ACTIONS API
# ============================================================

$apiLines = @(
'import { NextResponse } from "next/server";'
'import { supabaseAdmin } from "@/lib/supabase-admin";'
'import {'
'  apiErrorStatus,'
'  getAuthenticatedProfile,'
'} from "@/lib/api-auth";'
''
'// KLYX_BRAIN_MISSION_LIFECYCLE_12_78'
''
'type ActionKind ='
'  | "compare_offers"'
'  | "finalize_booking"'
'  | "payment_pending"'
'  | "track_mission"'
'  | "confirm_completion"'
'  | "review_completed"'
'  | "provider_offer_update"'
'  | "provider_booking_request"'
'  | "provider_track_mission"'
'  | "provider_finish_mission";'
''
'type ActionItem = {'
'  id: string;'
'  kind: ActionKind;'
'  priority: number;'
'  title: string;'
'  description: string;'
'  href: string;'
'  label: string;'
'};'
''
'type BookingRow = {'
'  id: string;'
'  parent_id: string;'
'  provider_id: string | null;'
'  babysitter_id: string | null;'
'  quote_id: string | null;'
'  status: string;'
'  payment_status: string | null;'
'  service_status: string | null;'
'  provider_finished_at: string | null;'
'  client_confirmed_at: string | null;'
'  booking_date: string;'
'  start_time: string;'
'  created_at: string;'
'};'
''
'type MarketRequestRow = {'
'  id: string;'
'  title: string;'
'  status: string;'
'  accepted_offer_id: string | null;'
'  created_at: string;'
'};'
''
'type OfferRow = {'
'  id: string;'
'  request_id: string;'
'  status: string;'
'};'
''
'type QuoteRow = {'
'  id: string;'
'  market_request_id: string | null;'
'  status: string;'
'};'
''
'function addAction('
'  map: Map<string, ActionItem>,'
'  action: ActionItem'
') {'
'  const existing = map.get(action.id);'
''
'  if (!existing || action.priority > existing.priority) {'
'    map.set(action.id, action);'
'  }'
'}'
''
'function missionDescription('
'  status: string | null'
') {'
'  if (status === "en_route") {'
'    return "Le prestataire est en route. Suis la mission en temps reel.";'
'  }'
''
'  if (status === "arrived") {'
'    return "Le prestataire indique etre arrive. La prestation va commencer.";'
'  }'
''
'  if (status === "in_progress") {'
'    return "La prestation est en cours. KLYX centralise son suivi.";'
'  }'
''
'  return "La mission est planifiee et son suivi est disponible.";'
'}'
''
'function missionPriority('
'  status: string | null'
') {'
'  if (status === "arrived") return 108;'
'  if (status === "en_route") return 104;'
'  if (status === "in_progress") return 102;'
'  return 80;'
'}'
''
'function providerMissionTitle('
'  status: string | null'
') {'
'  if (status === "en_route") {'
'    return "Continue ton trajet";'
'  }'
''
'  if (status === "arrived") {'
'    return "Demarre la prestation";'
'  }'
''
'  if (status === "in_progress") {'
'    return "Prestation en cours";'
'  }'
''
'  return "Mission prete a executer";'
'}'
''
'function providerMissionDescription('
'  status: string | null'
') {'
'  if (status === "en_route") {'
'    return "Indique ton arrivee au client depuis le suivi KLYX.";'
'  }'
''
'  if (status === "arrived") {'
'    return "Tu es arrive. Confirme le debut de la prestation.";'
'  }'
''
'  if (status === "in_progress") {'
'    return "Quand le travail est termine, declare la fin de mission.";'
'  }'
''
'  return "Le paiement est confirme. Tu peux commencer le suivi de la mission.";'
'}'
''
'export async function GET(request: Request) {'
'  try {'
'    const { profile } ='
'      await getAuthenticatedProfile(request);'
''
'    const actionMap ='
'      new Map<string, ActionItem>();'
''
'    let bookings: BookingRow[] = [];'
''
'    if (profile.accountType === "client") {'
'      const { data, error } ='
'        await supabaseAdmin'
'          .from("bookings")'
'          .select('
'            "id, parent_id, provider_id, babysitter_id, quote_id, status, payment_status, service_status, provider_finished_at, client_confirmed_at, booking_date, start_time, created_at"'
'          )'
'          .eq("parent_id", profile.id)'
'          .in("status", ['
'            "pending",'
'            "accepted",'
'            "completed",'
'          ])'
'          .order("created_at", {'
'            ascending: false,'
'          })'
'          .limit(50);'
''
'      if (error) {'
'        throw new Error(error.message);'
'      }'
''
'      bookings ='
'        (data ?? []) as BookingRow[];'
'    } else {'
'      const { data, error } ='
'        await supabaseAdmin'
'          .from("bookings")'
'          .select('
'            "id, parent_id, provider_id, babysitter_id, quote_id, status, payment_status, service_status, provider_finished_at, client_confirmed_at, booking_date, start_time, created_at"'
'          )'
'          .or('
'            "provider_id.eq." +'
'              profile.id +'
'              ",babysitter_id.eq." +'
'              profile.id'
'          )'
'          .in("status", ['
'            "pending",'
'            "accepted",'
'            "completed",'
'          ])'
'          .order("created_at", {'
'            ascending: false,'
'          })'
'          .limit(50);'
''
'      if (error) {'
'        throw new Error(error.message);'
'      }'
''
'      bookings ='
'        (data ?? []) as BookingRow[];'
'    }'
''
'    if (profile.accountType === "client") {'
'      const {'
'        data: marketData,'
'        error: marketError,'
'      } = await supabaseAdmin'
'        .from("market_service_requests")'
'        .select('
'          "id, title, status, accepted_offer_id, created_at"'
'        )'
'        .eq("client_profile_id", profile.id)'
'        .in("status", ['
'          "open",'
'          "matched",'
'        ])'
'        .order("created_at", {'
'          ascending: false,'
'        })'
'        .limit(30);'
''
'      if (marketError) {'
'        throw new Error(marketError.message);'
'      }'
''
'      const marketRequests ='
'        (marketData ?? []) as MarketRequestRow[];'
''
'      const requestIds ='
'        marketRequests.map('
'          (item) => item.id'
'        );'
''
'      let offers: OfferRow[] = [];'
'      let quotes: QuoteRow[] = [];'
''
'      if (requestIds.length > 0) {'
'        const [offersResult, quotesResult] ='
'          await Promise.all(['
'            supabaseAdmin'
'              .from("market_service_offers")'
'              .select('
'                "id, request_id, status"'
'              )'
'              .in("request_id", requestIds),'
''
'            supabaseAdmin'
'              .from("service_quotes")'
'              .select('
'                "id, market_request_id, status"'
'              )'
'              .in('
'                "market_request_id",'
'                requestIds'
'              ),'
'          ]);'
''
'        if (offersResult.error) {'
'          throw new Error('
'            offersResult.error.message'
'          );'
'        }'
''
'        if (quotesResult.error) {'
'          throw new Error('
'            quotesResult.error.message'
'          );'
'        }'
''
'        offers ='
'          (offersResult.data ?? []) as OfferRow[];'
''
'        quotes ='
'          (quotesResult.data ?? []) as QuoteRow[];'
'      }'
''
'      const quoteByRequest = new Map('
'        quotes'
'          .filter('
'            (item) =>'
'              Boolean(item.market_request_id)'
'          )'
'          .map((item) => ['
'            item.market_request_id as string,'
'            item,'
'          ])'
'      );'
''
'      const bookingByQuote = new Map('
'        bookings'
'          .filter('
'            (item) => Boolean(item.quote_id)'
'          )'
'          .map((item) => ['
'            item.quote_id as string,'
'            item,'
'          ])'
'      );'
''
'      for (const item of marketRequests) {'
'        const sentOffers = offers.filter('
'          (offer) =>'
'            offer.request_id === item.id &&'
'            offer.status === "sent"'
'        ).length;'
''
'        if ('
'          item.status === "open" &&'
'          sentOffers > 0'
'        ) {'
'          addAction(actionMap, {'
'            id: "compare-" + item.id,'
'            kind: "compare_offers",'
'            priority: 90,'
'            title:'
'              sentOffers +'
'              " offre" +'
'              (sentOffers > 1 ? "s" : "") +'
'              " a comparer",'
'            description: item.title,'
'            href:'
'              "/assistant/market/" +'
'              item.id,'
'            label: "Comparer avec KLYX",'
'          });'
'        }'
''
'        const quote ='
'          quoteByRequest.get(item.id);'
''
'        if (quote) {'
'          const booking ='
'            bookingByQuote.get(quote.id);'
''
'          if (!booking) {'
'            addAction(actionMap, {'
'              id: "finalize-" + item.id,'
'              kind: "finalize_booking",'
'              priority: 100,'
'              title:'
'                "Finaliser la reservation",'
'              description:'
'                "Le prestataire et le prix sont choisis. Il reste a confirmer le creneau.",'
'              href:'
'                "/quotes/" +'
'                quote.id +'
'                "/book",'
'              label: "Choisir le creneau",'
'            });'
'          }'
'        }'
'      }'
''
'      for (const booking of bookings) {'
'        if ('
'          booking.status === "accepted" &&'
'          booking.payment_status !== "paid"'
'        ) {'
'          addAction(actionMap, {'
'            id: "payment-" + booking.id,'
'            kind: "payment_pending",'
'            priority: 105,'
'            title: "Paiement a finaliser",'
'            description:'
'              "Le prestataire a accepte. Le paiement est la prochaine etape avant la mission.",'
'            href:'
'              "/bookings/" + booking.id,'
'            label: "Finaliser le paiement",'
'          });'
''
'          continue;'
'        }'
''
'        if ('
'          booking.status === "accepted" &&'
'          booking.payment_status === "paid"'
'        ) {'
'          if ('
'            booking.provider_finished_at &&'
'            !booking.client_confirmed_at'
'          ) {'
'            addAction(actionMap, {'
'              id:'
'                "confirm-completion-" +'
'                booking.id,'
'              kind: "confirm_completion",'
'              priority: 120,'
'              title: "Confirme la fin de mission",'
'              description:'
'                "Le prestataire a declare son travail termine. Verifie la prestation puis confirme.",'
'              href:'
'                "/tracking/" + booking.id,'
'              label: "Verifier et confirmer",'
'            });'
''
'            continue;'
'          }'
''
'          addAction(actionMap, {'
'            id: "track-" + booking.id,'
'            kind: "track_mission",'
'            priority: missionPriority('
'              booking.service_status'
'            ),'
'            title:'
'              booking.service_status === "arrived"'
'                ? "Le prestataire est arrive"'
'                : booking.service_status === "en_route"'
'                  ? "Le prestataire est en route"'
'                  : booking.service_status === "in_progress"'
'                    ? "Prestation en cours"'
'                    : "Mission planifiee",'
'            description: missionDescription('
'              booking.service_status'
'            ),'
'            href:'
'              "/tracking/" + booking.id,'
'            label: "Suivre la mission",'
'          });'
''
'          continue;'
'        }'
''
'        if (booking.status === "completed") {'
'          addAction(actionMap, {'
'            id: "review-" + booking.id,'
'            kind: "review_completed",'
'            priority: 60,'
'            title: "Mission terminee",'
'            description:'
'              "La mission est terminee. Consulte le resultat et laisse un avis si necessaire.",'
'            href:'
'              "/bookings/" + booking.id,'
'            label: "Voir la mission",'
'          });'
'        }'
'      }'
'    } else {'
'      const { data: offersData, error: offersError } ='
'        await supabaseAdmin'
'          .from("market_service_offers")'
'          .select('
'            "id, request_id, amount, status, updated_at"'
'          )'
'          .eq('
'            "provider_profile_id",'
'            profile.id'
'          )'
'          .in("status", ['
'            "sent",'
'            "accepted",'
'          ])'
'          .order("updated_at", {'
'            ascending: false,'
'          })'
'          .limit(30);'
''
'      if (offersError) {'
'        throw new Error(offersError.message);'
'      }'
''
'      for (const offer of offersData ?? []) {'
'        if (offer.status === "accepted") {'
'          addAction(actionMap, {'
'            id:'
'              "provider-accepted-" +'
'              offer.id,'
'            kind: "provider_offer_update",'
'            priority: 85,'
'            title: "Une offre a ete acceptee",'
'            description:'
'              "Montant accepte : " +'
'              Number(offer.amount).toFixed(2) +'
'              " EUR.",'
'            href: "/bookings",'
'            label: "Voir mes reservations",'
'          });'
'        }'
'      }'
''
'      for (const booking of bookings) {'
'        if (booking.status === "pending") {'
'          addAction(actionMap, {'
'            id:'
'              "provider-booking-" +'
'              booking.id,'
'            kind: "provider_booking_request",'
'            priority: 120,'
'            title: "Nouvelle reservation a traiter",'
'            description:'
'              "Un client attend ta reponse. Accepte ou refuse la demande.",'
'            href:'
'              "/bookings/" + booking.id,'
'            label: "Repondre maintenant",'
'          });'
''
'          continue;'
'        }'
''
'        if ('
'          booking.status !== "accepted" ||'
'          booking.payment_status !== "paid"'
'        ) {'
'          continue;'
'        }'
''
'        if ('
'          booking.provider_finished_at &&'
'          !booking.client_confirmed_at'
'        ) {'
'          continue;'
'        }'
''
'        if ('
'          booking.service_status ==='
'            "in_progress" &&'
'          !booking.provider_finished_at'
'        ) {'
'          addAction(actionMap, {'
'            id:'
'              "provider-finish-" +'
'              booking.id,'
'            kind: "provider_finish_mission",'
'            priority: 115,'
'            title: "Termine la mission dans KLYX",'
'            description:'
'              "La prestation est en cours. Quand le travail est fini, declare la mission terminee.",'
'            href:'
'              "/tracking/" + booking.id,'
'            label: "Declarer la fin",'
'          });'
''
'          continue;'
'        }'
''
'        addAction(actionMap, {'
'          id:'
'            "provider-track-" +'
'            booking.id,'
'          kind: "provider_track_mission",'
'          priority: missionPriority('
'            booking.service_status'
'          ) + 5,'
'          title: providerMissionTitle('
'            booking.service_status'
'          ),'
'          description:'
'            providerMissionDescription('
'              booking.service_status'
'            ),'
'          href:'
'            "/tracking/" + booking.id,'
'          label: "Ouvrir le suivi",'
'        });'
'      }'
'    }'
''
'    const actions ='
'      Array.from(actionMap.values())'
'        .sort('
'          (first, second) =>'
'            second.priority -'
'            first.priority'
'        );'
''
'    return NextResponse.json({'
'      profileId: profile.id,'
'      accountType: profile.accountType,'
'      actions: actions.slice(0, 20),'
'      count: actions.length,'
'    });'
'  } catch (error) {'
'    const message ='
'      error instanceof Error'
'        ? error.message'
'        : "Impossible de charger les actions KLYX.";'
''
'    return NextResponse.json('
'      { error: message },'
'      { status: apiErrorStatus(message) }'
'    );'
'  }'
'}'
)

$apiContent =
    [string]::Join(
        "`n",
        $apiLines
    )

# ============================================================
# ACTION CENTER UI
# ============================================================

$pageLines = @(
'"use client";'
''
'import Link from "next/link";'
'import {'
'  ArrowRight,'
'  CalendarCheck2,'
'  CheckCircle2,'
'  CreditCard,'
'  Flag,'
'  LoaderCircle,'
'  Navigation,'
'  RefreshCw,'
'  Sparkles,'
'  Star,'
'  TimerReset,'
'} from "lucide-react";'
'import {'
'  useCallback,'
'  useEffect,'
'  useState,'
'} from "react";'
'import { supabase } from "@/lib/supabase";'
''
'// KLYX_ACTION_CENTER_MISSION_UI_12_78'
''
'type ActionKind ='
'  | "compare_offers"'
'  | "finalize_booking"'
'  | "payment_pending"'
'  | "track_mission"'
'  | "confirm_completion"'
'  | "review_completed"'
'  | "provider_offer_update"'
'  | "provider_booking_request"'
'  | "provider_track_mission"'
'  | "provider_finish_mission";'
''
'type ActionItem = {'
'  id: string;'
'  kind: ActionKind;'
'  priority: number;'
'  title: string;'
'  description: string;'
'  href: string;'
'  label: string;'
'};'
''
'type ActionsResponse = {'
'  profileId: string;'
'  accountType: "client" | "provider";'
'  actions: ActionItem[];'
'  count: number;'
'};'
''
'async function token(): Promise<string> {'
'  const {'
'    data: { session },'
'  } = await supabase.auth.getSession();'
''
'  if (!session?.access_token) {'
'    throw new Error("Session manquante.");'
'  }'
''
'  return session.access_token;'
'}'
''
'function ActionIcon({'
'  kind,'
'}: {'
'  kind: ActionKind;'
'}) {'
'  if (kind === "payment_pending") {'
'    return <CreditCard size={20} />;'
'  }'
''
'  if (kind === "review_completed") {'
'    return <Star size={20} />;'
'  }'
''
'  if (kind === "finalize_booking") {'
'    return <TimerReset size={20} />;'
'  }'
''
'  if ('
'    kind === "track_mission" ||'
'    kind === "provider_track_mission"'
'  ) {'
'    return <Navigation size={20} />;'
'  }'
''
'  if (kind === "confirm_completion") {'
'    return <CheckCircle2 size={20} />;'
'  }'
''
'  if (kind === "provider_booking_request") {'
'    return <CalendarCheck2 size={20} />;'
'  }'
''
'  if (kind === "provider_finish_mission") {'
'    return <Flag size={20} />;'
'  }'
''
'  if (kind === "provider_offer_update") {'
'    return <CheckCircle2 size={20} />;'
'  }'
''
'  return <Sparkles size={20} />;'
'}'
''
'export default function AssistantActionsPage() {'
'  const [data, setData] ='
'    useState<ActionsResponse | null>(null);'
''
'  const [loading, setLoading] ='
'    useState(true);'
''
'  const [refreshing, setRefreshing] ='
'    useState(false);'
''
'  const [errorMessage, setErrorMessage] ='
'    useState("");'
''
'  const load = useCallback('
'    async (manual = false) => {'
'      if (manual) {'
'        setRefreshing(true);'
'      } else {'
'        setLoading(true);'
'      }'
''
'      setErrorMessage("");'
''
'      try {'
'        const accessToken = await token();'
''
'        const response = await fetch('
'          "/api/brain/actions",'
'          {'
'            cache: "no-store",'
'            headers: {'
'              Authorization:'
'                "Bearer " + accessToken,'
'            },'
'          }'
'        );'
''
'        const body ='
'          (await response.json()) as'
'            | ActionsResponse'
'            | { error?: string };'
''
'        if (!response.ok) {'
'          throw new Error('
'            "error" in body'
'              ? body.error ||'
'                  "Actions indisponibles."'
'              : "Actions indisponibles."'
'          );'
'        }'
''
'        setData(body as ActionsResponse);'
'      } catch (error) {'
'        setErrorMessage('
'          error instanceof Error'
'            ? error.message'
'            : "Actions indisponibles."'
'        );'
'      } finally {'
'        setLoading(false);'
'        setRefreshing(false);'
'      }'
'    },'
'    []'
'  );'
''
'  useEffect(() => {'
'    void load(false);'
'  }, [load]);'
''
'  return ('
'    <main className="klyx-page">'
'      <div className="mx-auto max-w-6xl">'
'        <section className="rounded-[2rem] border border-white/10 bg-[linear-gradient(135deg,#17131f,#4c1d95_52%,#111827)] p-7 text-white sm:p-10">'
'          <div className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/5 px-3 py-1.5 text-xs font-black uppercase tracking-[0.18em] text-white/70">'
'            <Sparkles size={14} />'
'            KLYX Action Center'
'          </div>'
''
'          <h1 className="mt-4 text-3xl font-black sm:text-5xl">'
'            Ce que KLYX te recommande maintenant'
'          </h1>'
''
'          <p className="mt-4 max-w-3xl text-sm leading-7 text-white/70">'
'            Offres, reservation, paiement et execution de mission sont maintenant reunis dans un seul ordre de priorite.'
'          </p>'
'        </section>'
''
'        <div className="mt-6 flex items-center justify-between gap-3">'
'          <div>'
'            <p className="text-sm font-black">'
'              {data?.count ?? 0} action'
'              {(data?.count ?? 0) > 1 ? "s" : ""}'
'            </p>'
''
'            <p className="text-xs text-muted-foreground">'
'              Profil{" "}'
'              {data?.accountType === "provider"'
'                ? "prestataire"'
'                : "client"}'
'            </p>'
'          </div>'
''
'          <button'
'            type="button"'
'            disabled={refreshing}'
'            onClick={() => void load(true)}'
'            className="inline-flex min-h-10 items-center gap-2 rounded-xl border border-border bg-background px-3 text-xs font-black hover:bg-muted disabled:opacity-50"'
'          >'
'            {refreshing ? ('
'              <LoaderCircle'
'                className="animate-spin"'
'                size={15}'
'              />'
'            ) : ('
'              <RefreshCw size={15} />'
'            )}'
'            Actualiser'
'          </button>'
'        </div>'
''
'        {errorMessage && ('
'          <div className="mt-5 rounded-2xl border border-rose-500/25 bg-rose-500/10 p-4 text-sm text-rose-700 dark:text-rose-300">'
'            {errorMessage}'
'          </div>'
'        )}'
''
'        {loading ? ('
'          <div className="grid min-h-72 place-items-center">'
'            <LoaderCircle'
'              className="animate-spin text-violet-600"'
'              size={36}'
'            />'
'          </div>'
'        ) : !data ||'
'          data.actions.length === 0 ? ('
'          <section className="klyx-card mt-6 p-8 text-center">'
'            <div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-emerald-500/10 text-emerald-600">'
'              <CheckCircle2 size={24} />'
'            </div>'
''
'            <h2 className="mt-5 text-xl font-black">'
'              Rien a faire maintenant'
'            </h2>'
''
'            <p className="mt-2 text-sm text-muted-foreground">'
'              KLYX ne detecte aucune action necessaire pour ce profil.'
'            </p>'
'          </section>'
'        ) : ('
'          <section className="mt-6 grid gap-4">'
'            {data.actions.map('
'              (action, index) => ('
'                <article'
'                  key={action.id}'
'                  className="klyx-card grid gap-5 p-5 sm:grid-cols-[52px_1fr_auto] sm:items-center sm:p-6"'
'                >'
'                  <div className="grid h-12 w-12 place-items-center rounded-2xl bg-violet-500/10 text-violet-600">'
'                    <ActionIcon'
'                      kind={action.kind}'
'                    />'
'                  </div>'
''
'                  <div>'
'                    <div className="flex flex-wrap items-center gap-2">'
'                      <span className="text-xs font-black uppercase tracking-[0.14em] text-muted-foreground">'
'                        Priorite {index + 1}'
'                      </span>'
''
'                      {action.priority >= 105 && ('
'                        <span className="rounded-full bg-rose-500/10 px-2.5 py-1 text-[10px] font-black uppercase text-rose-700 dark:text-rose-300">'
'                          Important'
'                        </span>'
'                      )}'
'                    </div>'
''
'                    <h2 className="mt-2 text-lg font-black">'
'                      {action.title}'
'                    </h2>'
''
'                    <p className="mt-1 max-w-3xl text-sm leading-6 text-muted-foreground">'
'                      {action.description}'
'                    </p>'
'                  </div>'
''
'                  <Link'
'                    href={action.href}'
'                    className="klyx-button"'
'                  >'
'                    {action.label}'
'                    <ArrowRight size={17} />'
'                  </Link>'
'                </article>'
'              )'
'            )}'
'          </section>'
'        )}'
'      </div>'
'    </main>'
'  );'
'}'
)

$pageContent =
    [string]::Join(
        "`n",
        $pageLines
    )

# ============================================================
# VALIDATION
# ============================================================

$checks = @(
    @{
        Name = "Brain lifecycle"
        Value = $apiContent.Contains(
            "KLYX_BRAIN_MISSION_LIFECYCLE_12_78"
        )
    },
    @{
        Name = "client payment"
        Value = $apiContent.Contains(
            '"payment_pending"'
        )
    },
    @{
        Name = "client tracking"
        Value = $apiContent.Contains(
            '"track_mission"'
        )
    },
    @{
        Name = "client confirmation"
        Value = $apiContent.Contains(
            '"confirm_completion"'
        )
    },
    @{
        Name = "provider booking"
        Value = $apiContent.Contains(
            '"provider_booking_request"'
        )
    },
    @{
        Name = "provider tracking"
        Value = $apiContent.Contains(
            '"provider_track_mission"'
        )
    },
    @{
        Name = "provider finish"
        Value = $apiContent.Contains(
            '"provider_finish_mission"'
        )
    },
    @{
        Name = "UI lifecycle"
        Value = $pageContent.Contains(
            "KLYX_ACTION_CENTER_MISSION_UI_12_78"
        )
    }
)

foreach ($check in $checks) {
    if (-not $check.Value) {
        throw "12.78 validation failed : $($check.Name)"
    }
}

# ============================================================
# BACKUPS
# ============================================================

$timestamp =
    Get-Date -Format "yyyyMMdd-HHmmss"

foreach ($path in @(
    $apiPath,
    $pagePath
)) {
    Copy-Item `
        -LiteralPath $path `
        -Destination (
            $path +
            ".bak-12-78-" +
            $timestamp
        ) `
        -Force
}

# ============================================================
# WRITE
# ============================================================

[System.IO.File]::WriteAllText(
    $apiPath,
    $apiContent,
    $utf8NoBom
)

[System.IO.File]::WriteAllText(
    $pagePath,
    $pageContent,
    $utf8NoBom
)

Write-Host ""
Write-Host "======================================"
Write-Host "KLYX 12.78 APPLIQUE"
Write-Host "======================================"
Write-Host "Brain connecte aux reservations."
Write-Host "Brain connecte aux paiements."
Write-Host "Brain connecte au suivi de mission."
Write-Host "Client et prestataire ont leur prochaine action."
Write-Host ""