$ErrorActionPreference = "Stop"

$projectRoot = Split-Path -Parent $PSScriptRoot

$apiPath = Join-Path `
    $projectRoot `
    "app\api\bookings\[id]\contact\route.ts"

$componentPath = Join-Path `
    $projectRoot `
    "app\components\BookingContactCard.tsx"

Write-Host ""
Write-Host "KLYX 12.74 - Revalidated Call + Auto Remask"
Write-Host ""

foreach ($path in @(
    $apiPath,
    $componentPath
)) {
    if (-not (Test-Path -LiteralPath $path)) {
        throw "Fichier introuvable : $path"
    }
}

$utf8NoBom =
    New-Object System.Text.UTF8Encoding($false)

# ============================================================
# API COMPLETE
# GET  = eligibility
# POST = reveal
# PUT  = revalidated call
# ============================================================

$apiLines = @(
'import { NextResponse } from "next/server";'
''
'import {'
'  apiErrorStatus,'
'  getAuthenticatedProfile,'
'} from "@/lib/api-auth";'
'import { supabaseAdmin } from "@/lib/supabase-admin";'
''
'// KLYX_REVALIDATED_PHONE_CALL_API_12_74'
''
'type BookingRow = {'
'  id: string;'
'  parent_id: string;'
'  provider_id: string | null;'
'  babysitter_id: string | null;'
'  status: string;'
'  completed_at: string | null;'
'};'
''
'type ContactProfileRow = {'
'  id: string;'
'  first_name: string | null;'
'  last_name: string | null;'
'  phone_number: string | null;'
'  phone_verified_at: string | null;'
'  phone_visibility: string | null;'
'};'
''
'type ReadyContact = {'
'  booking: BookingRow;'
'  viewerProfileId: string;'
'  otherProfile: ContactProfileRow;'
'  otherName: string;'
'  phoneNumber: string;'
'  accessExpiresAt: string | null;'
'};'
''
'type DeniedContact = {'
'  response: NextResponse;'
'};'
''
'const COMPLETED_CONTACT_HOURS = 24;'
'const DISPLAY_MINUTES = 5;'
''
'function formatName('
'  profile: ContactProfileRow'
') {'
'  return ('
'    [profile.first_name, profile.last_name]'
'      .filter(Boolean)'
'      .join(" ") ||'
'    "Utilisateur KLYX"'
'  );'
'}'
''
'function isTransactionVisible('
'  profile: ContactProfileRow'
') {'
'  return ('
'    profile.phone_visibility == null ||'
'    profile.phone_visibility ==='
'      "transaction_participants"'
'  );'
'}'
''
'function completedAccessExpiresAt('
'  completedAt: string'
') {'
'  return new Date('
'    new Date(completedAt).getTime() +'
'      COMPLETED_CONTACT_HOURS * 60 * 60 * 1000'
'  );'
'}'
''
'function displayExpiresAt() {'
'  return new Date('
'    Date.now() +'
'      DISPLAY_MINUTES * 60 * 1000'
'  ).toISOString();'
'}'
''
'async function resolveContact('
'  request: Request,'
'  bookingId: string'
'): Promise<ReadyContact | DeniedContact> {'
'  const { profile } ='
'    await getAuthenticatedProfile(request);'
''
'  const { data, error } ='
'    await supabaseAdmin'
'      .from("bookings")'
'      .select('
'        "id, parent_id, provider_id, babysitter_id, status, completed_at"'
'      )'
'      .eq("id", bookingId)'
'      .maybeSingle();'
''
'  if (error) {'
'    throw new Error(error.message);'
'  }'
''
'  if (!data) {'
'    return {'
'      response: NextResponse.json('
'        { error: "Reservation introuvable." },'
'        { status: 404 }'
'      ),'
'    };'
'  }'
''
'  const booking = data as BookingRow;'
''
'  const providerId ='
'    booking.provider_id ??'
'    booking.babysitter_id;'
''
'  if (!providerId) {'
'    return {'
'      response: NextResponse.json('
'        { error: "Prestataire introuvable." },'
'        { status: 409 }'
'      ),'
'    };'
'  }'
''
'  const isClient ='
'    booking.parent_id === profile.id;'
''
'  const isProvider ='
'    providerId === profile.id;'
''
'  if (!isClient && !isProvider) {'
'    return {'
'      response: NextResponse.json('
'        { error: "Acces refuse." },'
'        { status: 403 }'
'      ),'
'    };'
'  }'
''
'  if ('
'    booking.status !== "accepted" &&'
'    booking.status !== "completed"'
'  ) {'
'    return {'
'      response: NextResponse.json({'
'        contactAllowed: false,'
'        canReveal: false,'
'        reason: "status_not_allowed",'
'        message:'
'          "Le contact est disponible uniquement pour une mission acceptee.",'
'      }),'
'    };'
'  }'
''
'  let accessExpiresAt: string | null = null;'
''
'  if (booking.status === "completed") {'
'    if (!booking.completed_at) {'
'      return {'
'        response: NextResponse.json({'
'          contactAllowed: false,'
'          canReveal: false,'
'          reason: "missing_completion_time",'
'          message:'
'            "La periode de contact ne peut pas etre determinee.",'
'        }),'
'      };'
'    }'
''
'    const expiresAt ='
'      completedAccessExpiresAt('
'        booking.completed_at'
'      );'
''
'    accessExpiresAt ='
'      expiresAt.toISOString();'
''
'    if (expiresAt.getTime() <= Date.now()) {'
'      return {'
'        response: NextResponse.json({'
'          contactAllowed: false,'
'          canReveal: false,'
'          reason: "contact_expired",'
'          accessExpiresAt,'
'          message:'
'            "La periode de contact telephonique est terminee.",'
'        }),'
'      };'
'    }'
'  }'
''
'  const otherProfileId ='
'    isClient'
'      ? providerId'
'      : booking.parent_id;'
''
'  const {'
'    data: profilesData,'
'    error: profilesError,'
'  } = await supabaseAdmin'
'    .from("profiles")'
'    .select('
'      "id, first_name, last_name, phone_number, phone_verified_at, phone_visibility"'
'    )'
'    .in("id", ['
'      profile.id,'
'      otherProfileId,'
'    ]);'
''
'  if (profilesError) {'
'    throw new Error('
'      profilesError.message'
'    );'
'  }'
''
'  const profiles ='
'    (profilesData ?? []) as ContactProfileRow[];'
''
'  const ownProfile ='
'    profiles.find('
'      (item) => item.id === profile.id'
'    );'
''
'  const otherProfile ='
'    profiles.find('
'      (item) => item.id === otherProfileId'
'    );'
''
'  if (!ownProfile || !otherProfile) {'
'    return {'
'      response: NextResponse.json('
'        { error: "Profil de contact introuvable." },'
'        { status: 404 }'
'      ),'
'    };'
'  }'
''
'  const otherName ='
'    formatName(otherProfile);'
''
'  const ownPhone ='
'    ownProfile.phone_number?.trim() ?? "";'
''
'  if (!ownPhone) {'
'    return {'
'      response: NextResponse.json({'
'        contactAllowed: true,'
'        canReveal: false,'
'        otherName,'
'        accessExpiresAt,'
'        actionRequired: "verify_own_phone",'
'        reason: "own_missing_phone",'
'        message:'
'          "Ajoute ton numero avant d acceder au contact.",'
'      }),'
'    };'
'  }'
''
'  if (!ownProfile.phone_verified_at) {'
'    return {'
'      response: NextResponse.json({'
'        contactAllowed: true,'
'        canReveal: false,'
'        otherName,'
'        accessExpiresAt,'
'        actionRequired: "verify_own_phone",'
'        reason: "own_unverified_phone",'
'        message:'
'          "Verifie ton numero par SMS avant d acceder au contact.",'
'      }),'
'    };'
'  }'
''
'  if (!isTransactionVisible(ownProfile)) {'
'    return {'
'      response: NextResponse.json({'
'        contactAllowed: true,'
'        canReveal: false,'
'        otherName,'
'        accessExpiresAt,'
'        actionRequired: "verify_own_phone",'
'        reason: "own_private_phone",'
'        message:'
'          "Ton numero est actuellement prive.",'
'      }),'
'    };'
'  }'
''
'  const otherPhone ='
'    otherProfile.phone_number?.trim() ?? "";'
''
'  if (!otherPhone) {'
'    return {'
'      response: NextResponse.json({'
'        contactAllowed: true,'
'        canReveal: false,'
'        otherName,'
'        accessExpiresAt,'
'        reason: "other_missing_phone",'
'        message:'
'          otherName +'
'          " n a pas encore ajoute de numero.",'
'      }),'
'    };'
'  }'
''
'  if (!otherProfile.phone_verified_at) {'
'    return {'
'      response: NextResponse.json({'
'        contactAllowed: true,'
'        canReveal: false,'
'        otherName,'
'        accessExpiresAt,'
'        reason: "other_unverified_phone",'
'        message:'
'          "Le numero de " +'
'          otherName +'
'          " doit encore etre verifie.",'
'      }),'
'    };'
'  }'
''
'  if (!isTransactionVisible(otherProfile)) {'
'    return {'
'      response: NextResponse.json({'
'        contactAllowed: true,'
'        canReveal: false,'
'        otherName,'
'        accessExpiresAt,'
'        reason: "other_private_phone",'
'        message:'
'          otherName +'
'          " ne partage pas son numero.",'
'      }),'
'    };'
'  }'
''
'  return {'
'    booking,'
'    viewerProfileId: profile.id,'
'    otherProfile,'
'    otherName,'
'    phoneNumber: otherPhone,'
'    accessExpiresAt,'
'  };'
'}'
''
'function isDenied('
'  value: ReadyContact | DeniedContact'
'): value is DeniedContact {'
'  return "response" in value;'
'}'
''
'async function addAuditLog('
'  result: ReadyContact,'
'  eventType: string'
') {'
'  const { error } ='
'    await supabaseAdmin'
'      .from("phone_contact_access_logs")'
'      .insert({'
'        booking_id: result.booking.id,'
'        viewer_profile_id:'
'          result.viewerProfileId,'
'        contact_profile_id:'
'          result.otherProfile.id,'
'        event_type: eventType,'
'      });'
''
'  if (error) {'
'    throw new Error('
'      "Journal de securite indisponible : " +'
'        error.message'
'    );'
'  }'
'}'
''
'export async function GET('
'  request: Request,'
'  context: {'
'    params: Promise<{ id: string }>;'
'  }'
') {'
'  try {'
'    const { id: bookingId } ='
'      await context.params;'
''
'    const result ='
'      await resolveContact('
'        request,'
'        bookingId'
'      );'
''
'    if (isDenied(result)) {'
'      return result.response;'
'    }'
''
'    return NextResponse.json({'
'      contactAllowed: true,'
'      canReveal: true,'
'      otherName: result.otherName,'
'      phoneNumber: null,'
'      accessExpiresAt:'
'        result.accessExpiresAt,'
'    });'
'  } catch (error) {'
'    const message ='
'      error instanceof Error'
'        ? error.message'
'        : "Contact KLYX indisponible.";'
''
'    return NextResponse.json('
'      { error: message },'
'      { status: apiErrorStatus(message) }'
'    );'
'  }'
'}'
''
'export async function POST('
'  request: Request,'
'  context: {'
'    params: Promise<{ id: string }>;'
'  }'
') {'
'  try {'
'    const { id: bookingId } ='
'      await context.params;'
''
'    const result ='
'      await resolveContact('
'        request,'
'        bookingId'
'      );'
''
'    if (isDenied(result)) {'
'      return result.response;'
'    }'
''
'    await addAuditLog('
'      result,'
'      "phone_explicit_reveal"'
'    );'
''
'    return NextResponse.json({'
'      contactAllowed: true,'
'      canReveal: true,'
'      revealed: true,'
'      audited: true,'
'      otherName: result.otherName,'
'      phoneNumber: result.phoneNumber,'
'      verified: true,'
'      accessExpiresAt:'
'        result.accessExpiresAt,'
'      displayExpiresAt:'
'        displayExpiresAt(),'
'    });'
'  } catch (error) {'
'    const message ='
'      error instanceof Error'
'        ? error.message'
'        : "Revelation impossible.";'
''
'    return NextResponse.json('
'      { error: message },'
'      { status: apiErrorStatus(message) }'
'    );'
'  }'
'}'
''
'export async function PUT('
'  request: Request,'
'  context: {'
'    params: Promise<{ id: string }>;'
'  }'
') {'
'  try {'
'    const { id: bookingId } ='
'      await context.params;'
''
'    const result ='
'      await resolveContact('
'        request,'
'        bookingId'
'      );'
''
'    if (isDenied(result)) {'
'      return result.response;'
'    }'
''
'    await addAuditLog('
'      result,'
'      "phone_call_started"'
'    );'
''
'    return NextResponse.json({'
'      callAllowed: true,'
'      audited: true,'
'      phoneNumber: result.phoneNumber,'
'    });'
'  } catch (error) {'
'    const message ='
'      error instanceof Error'
'        ? error.message'
'        : "Appel KLYX impossible.";'
''
'    return NextResponse.json('
'      { error: message },'
'      { status: apiErrorStatus(message) }'
'    );'
'  }'
'}'
)

$apiContent =
    [string]::Join(
        "`n",
        $apiLines
    )

# ============================================================
# UI COMPLETE
# ============================================================

$componentLines = @(
'"use client";'
''
'import Link from "next/link";'
'import {'
'  useCallback,'
'  useEffect,'
'  useState,'
'} from "react";'
'import {'
'  CheckCircle2,'
'  Clock3,'
'  Eye,'
'  EyeOff,'
'  LoaderCircle,'
'  LockKeyhole,'
'  Phone,'
'  ShieldCheck,'
'  Smartphone,'
'} from "lucide-react";'
''
'import { supabase } from "@/lib/supabase";'
''
'// KLYX_REVALIDATED_PHONE_CALL_UI_12_74'
''
'type ContactPayload = {'
'  contactAllowed?: boolean;'
'  canReveal?: boolean;'
'  revealed?: boolean;'
'  audited?: boolean;'
'  phoneNumber?: string | null;'
'  otherName?: string;'
'  verified?: boolean;'
'  accessExpiresAt?: string | null;'
'  displayExpiresAt?: string | null;'
'  reason?: string;'
'  actionRequired?: string;'
'  message?: string;'
'  error?: string;'
'};'
''
'type CallPayload = {'
'  callAllowed?: boolean;'
'  phoneNumber?: string;'
'  error?: string;'
'};'
''
'type Props = {'
'  bookingId: string;'
'  bookingStatus: string;'
'  otherName: string;'
'};'
''
'function formatExpiry(value: string) {'
'  return new Intl.DateTimeFormat('
'    "fr-BE",'
'    {'
'      day: "2-digit",'
'      month: "2-digit",'
'      hour: "2-digit",'
'      minute: "2-digit",'
'    }'
'  ).format(new Date(value));'
'}'
''
'export default function BookingContactCard({'
'  bookingId,'
'  bookingStatus,'
'  otherName,'
'}: Props) {'
'  const [loading, setLoading] ='
'    useState(false);'
''
'  const [revealing, setRevealing] ='
'    useState(false);'
''
'  const [calling, setCalling] ='
'    useState(false);'
''
'  const [payload, setPayload] ='
'    useState<ContactPayload | null>(null);'
''
'  const statusAllowsContact ='
'    bookingStatus === "accepted" ||'
'    bookingStatus === "completed";'
''
'  async function getToken() {'
'    const { data } ='
'      await supabase.auth.getSession();'
''
'    const accessToken ='
'      data.session?.access_token;'
''
'    if (!accessToken) {'
'      throw new Error('
'        "Session KLYX introuvable."'
'      );'
'    }'
''
'    return accessToken;'
'  }'
''
'  const loadEligibility ='
'    useCallback(async () => {'
'      if (!statusAllowsContact) return;'
''
'      setLoading(true);'
''
'      try {'
'        const accessToken ='
'          await getToken();'
''
'        const response = await fetch('
'          "/api/bookings/" +'
'            encodeURIComponent(bookingId) +'
'            "/contact",'
'          {'
'            cache: "no-store",'
'            headers: {'
'              Authorization:'
'                "Bearer " + accessToken,'
'            },'
'          }'
'        );'
''
'        const result ='
'          (await response.json()) as ContactPayload;'
''
'        if (!response.ok) {'
'          throw new Error('
'            result.error ||'
'              "Contact indisponible."'
'          );'
'        }'
''
'        setPayload(result);'
'      } catch (error) {'
'        setPayload({'
'          canReveal: false,'
'          error:'
'            error instanceof Error'
'              ? error.message'
'              : "Contact indisponible.",'
'        });'
'      } finally {'
'        setLoading(false);'
'      }'
'    }, [bookingId, statusAllowsContact]);'
''
'  useEffect(() => {'
'    setPayload(null);'
''
'    if (statusAllowsContact) {'
'      void loadEligibility();'
'    }'
'  }, ['
'    statusAllowsContact,'
'    loadEligibility,'
'  ]);'
''
'  useEffect(() => {'
'    if ('
'      !payload?.revealed ||'
'      !payload.displayExpiresAt'
'    ) {'
'      return;'
'    }'
''
'    const delay ='
'      new Date('
'        payload.displayExpiresAt'
'      ).getTime() - Date.now();'
''
'    if (delay <= 0) {'
'      setPayload((current) =>'
'        current'
'          ? {'
'              ...current,'
'              revealed: false,'
'              phoneNumber: null,'
'              displayExpiresAt: null,'
'            }'
'          : current'
'      );'
'      return;'
'    }'
''
'    const timer = window.setTimeout(() => {'
'      setPayload((current) =>'
'        current'
'          ? {'
'              ...current,'
'              revealed: false,'
'              phoneNumber: null,'
'              displayExpiresAt: null,'
'            }'
'          : current'
'      );'
'    }, delay);'
''
'    return () =>'
'      window.clearTimeout(timer);'
'  }, ['
'    payload?.displayExpiresAt,'
'    payload?.revealed,'
'  ]);'
''
'  async function revealPhone() {'
'    setRevealing(true);'
''
'    try {'
'      const accessToken ='
'        await getToken();'
''
'      const response = await fetch('
'        "/api/bookings/" +'
'          encodeURIComponent(bookingId) +'
'          "/contact",'
'        {'
'          method: "POST",'
'          cache: "no-store",'
'          headers: {'
'            Authorization:'
'              "Bearer " + accessToken,'
'          },'
'        }'
'      );'
''
'      const result ='
'        (await response.json()) as ContactPayload;'
''
'      if (!response.ok) {'
'        throw new Error('
'          result.error ||'
'            "Impossible d afficher le numero."'
'        );'
'      }'
''
'      setPayload(result);'
'    } catch (error) {'
'      setPayload((current) => ({'
'        ...current,'
'        error:'
'          error instanceof Error'
'            ? error.message'
'            : "Impossible d afficher le numero.",'
'      }));'
'    } finally {'
'      setRevealing(false);'
'    }'
'  }'
''
'  function hidePhone() {'
'    setPayload((current) =>'
'      current'
'        ? {'
'            ...current,'
'            revealed: false,'
'            phoneNumber: null,'
'            displayExpiresAt: null,'
'          }'
'        : current'
'    );'
'  }'
''
'  async function startCall() {'
'    setCalling(true);'
''
'    try {'
'      const accessToken ='
'        await getToken();'
''
'      const response = await fetch('
'        "/api/bookings/" +'
'          encodeURIComponent(bookingId) +'
'          "/contact",'
'        {'
'          method: "PUT",'
'          cache: "no-store",'
'          headers: {'
'            Authorization:'
'              "Bearer " + accessToken,'
'          },'
'        }'
'      );'
''
'      const result ='
'        (await response.json()) as CallPayload;'
''
'      if ('
'        !response.ok ||'
'        !result.callAllowed ||'
'        !result.phoneNumber'
'      ) {'
'        throw new Error('
'          result.error ||'
'            "L appel n est plus autorise."'
'        );'
'      }'
''
'      window.location.href ='
'        "tel:" + result.phoneNumber;'
'    } catch (error) {'
'      const message ='
'        error instanceof Error'
'          ? error.message'
'          : "Appel impossible.";'
''
'      setPayload((current) => ({'
'        ...current,'
'        revealed: false,'
'        phoneNumber: null,'
'        displayExpiresAt: null,'
'        error: message,'
'      }));'
''
'      await loadEligibility();'
'    } finally {'
'      setCalling(false);'
'    }'
'  }'
''
'  if (!statusAllowsContact) {'
'    return ('
'      <div className="mt-4 rounded-2xl border border-border bg-muted/30 p-4">'
'        <div className="flex items-start gap-3">'
'          <LockKeyhole'
'            size={20}'
'            className="mt-0.5 text-muted-foreground"'
'          />'
''
'          <div>'
'            <p className="font-black">'
'              Contact protege'
'            </p>'
'            <p className="mt-1 text-sm text-muted-foreground">'
'              Le contact devient disponible apres acceptation.'
'            </p>'
'          </div>'
'        </div>'
'      </div>'
'    );'
'  }'
''
'  if (loading || !payload) {'
'    return ('
'      <div className="mt-4 flex items-center gap-3 rounded-2xl border border-border bg-muted/30 p-4 text-sm text-muted-foreground">'
'        <LoaderCircle'
'          size={18}'
'          className="animate-spin"'
'        />'
'        Verification du contact...'
'      </div>'
'    );'
'  }'
''
'  const ownAction ='
'    payload.actionRequired ==='
'    "verify_own_phone";'
''
'  if (!payload.canReveal) {'
'    return ('
'      <div className="mt-4 rounded-2xl border border-border bg-muted/30 p-5">'
'        <div className="flex items-start gap-3">'
'          {ownAction ? ('
'            <Smartphone'
'              size={20}'
'              className="mt-0.5 text-amber-500"'
'            />'
'          ) : ('
'            <ShieldCheck'
'              size={20}'
'              className="mt-0.5 text-violet-500"'
'            />'
'          )}'
''
'          <div>'
'            <p className="font-black">'
'              {payload.reason === "contact_expired"'
'                ? "Contact expire"'
'                : "Contact KLYX protege"}'
'            </p>'
''
'            <p className="mt-1 text-sm text-muted-foreground">'
'              {payload.error ||'
'                payload.message ||'
'                "Contact indisponible."}'
'            </p>'
''
'            {ownAction && ('
'              <Link'
'                href="/settings"'
'                className="mt-4 inline-flex h-11 items-center gap-2 rounded-xl bg-violet-600 px-5 text-sm font-black text-white"'
'              >'
'                <Smartphone size={17} />'
'                Verifier mon numero'
'              </Link>'
'            )}'
'          </div>'
'        </div>'
'      </div>'
'    );'
'  }'
''
'  const name ='
'    payload.otherName || otherName;'
''
'  if (!payload.revealed || !payload.phoneNumber) {'
'    return ('
'      <div className="mt-4 rounded-2xl border border-violet-500/25 bg-violet-500/[0.05] p-5">'
'        <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">'
'          <div>'
'            <p className="font-black">'
'              Contact de {name}'
'            </p>'
''
'            <p className="mt-2 text-sm text-muted-foreground">'
'              Le numero reste masque jusqu a ta demande.'
'            </p>'
''
'            {payload.accessExpiresAt && ('
'              <p className="mt-2 flex items-center gap-1 text-xs text-amber-500">'
'                <Clock3 size={14} />'
'                Disponible jusqu au{" "}'
'                {formatExpiry('
'                  payload.accessExpiresAt'
'                )}'
'              </p>'
'            )}'
'          </div>'
''
'          <button'
'            type="button"'
'            disabled={revealing}'
'            onClick={() =>'
'              void revealPhone()'
'            }'
'            className="inline-flex h-12 items-center justify-center gap-2 rounded-2xl bg-violet-600 px-6 text-sm font-black text-white disabled:opacity-60"'
'          >'
'            {revealing ? ('
'              <LoaderCircle'
'                size={18}'
'                className="animate-spin"'
'              />'
'            ) : ('
'              <Eye size={18} />'
'            )}'
'            Afficher le numero'
'          </button>'
'        </div>'
''
'        {payload.error && ('
'          <div className="mt-4 rounded-xl bg-rose-500/10 px-4 py-3 text-sm font-bold text-rose-500">'
'            {payload.error}'
'          </div>'
'        )}'
'      </div>'
'    );'
'  }'
''
'  return ('
'    <div className="mt-4 rounded-2xl border border-emerald-500/25 bg-emerald-500/[0.06] p-5">'
'      <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">'
'        <div className="min-w-0">'
'          <div className="flex flex-wrap items-center gap-2">'
'            <Phone'
'              size={18}'
'              className="text-emerald-500"'
'            />'
'            <p className="font-black">'
'              {name}'
'            </p>'
'            <span className="inline-flex items-center gap-1 rounded-full bg-emerald-500/10 px-2 py-1 text-xs font-black text-emerald-500">'
'              <CheckCircle2 size={13} />'
'              Verifie'
'            </span>'
'          </div>'
''
'          <p className="mt-2 break-all text-lg font-black">'
'            {payload.phoneNumber}'
'          </p>'
''
'          <p className="mt-1 text-xs text-muted-foreground">'
'            Le numero sera remasque automatiquement apres 5 minutes.'
'          </p>'
'        </div>'
''
'        <div className="flex flex-col gap-2 sm:flex-row">'
'          <button'
'            type="button"'
'            onClick={hidePhone}'
'            className="inline-flex h-12 items-center justify-center gap-2 rounded-2xl border border-border px-5 text-sm font-black"'
'          >'
'            <EyeOff size={18} />'
'            Masquer'
'          </button>'
''
'          <button'
'            type="button"'
'            disabled={calling}'
'            onClick={() =>'
'              void startCall()'
'            }'
'            className="inline-flex h-12 items-center justify-center gap-2 rounded-2xl bg-emerald-600 px-6 text-sm font-black text-white disabled:opacity-60"'
'          >'
'            {calling ? ('
'              <LoaderCircle'
'                size={18}'
'                className="animate-spin"'
'              />'
'            ) : ('
'              <Phone size={18} />'
'            )}'
'            Appeler'
'          </button>'
'        </div>'
'      </div>'
'    </div>'
'  );'
'}'
)

$componentContent =
    [string]::Join(
        "`n",
        $componentLines
    )

# ============================================================
# VALIDATION
# ============================================================

$checks = @(
    @{
        Name = "API marker"
        Value = $apiContent.Contains(
            "KLYX_REVALIDATED_PHONE_CALL_API_12_74"
        )
    },
    @{
        Name = "PUT call"
        Value = $apiContent.Contains(
            "export async function PUT"
        )
    },
    @{
        Name = "call audit"
        Value = $apiContent.Contains(
            '"phone_call_started"'
        )
    },
    @{
        Name = "5 minute display"
        Value = $apiContent.Contains(
            "DISPLAY_MINUTES = 5"
        )
    },
    @{
        Name = "UI marker"
        Value = $componentContent.Contains(
            "KLYX_REVALIDATED_PHONE_CALL_UI_12_74"
        )
    },
    @{
        Name = "call uses PUT"
        Value = $componentContent.Contains(
            'method: "PUT"'
        )
    },
    @{
        Name = "auto remask"
        Value = $componentContent.Contains(
            "displayExpiresAt"
        )
    },
    @{
        Name = "manual hide"
        Value = $componentContent.Contains(
            "function hidePhone()"
        )
    }
)

foreach ($check in $checks) {
    if (-not $check.Value) {
        throw "12.74 validation failed : $($check.Name)"
    }
}

# ============================================================
# BACKUPS
# ============================================================

$timestamp =
    Get-Date -Format "yyyyMMdd-HHmmss"

foreach ($path in @(
    $apiPath,
    $componentPath
)) {
    Copy-Item `
        -LiteralPath $path `
        -Destination (
            $path +
            ".bak-12-74-" +
            $timestamp
        ) `
        -Force
}

# ============================================================
# WRITE
# ============================================================

[System.IO.File]::WriteAllText(
    $apiPath,
    $apiContent,
    $utf8NoBom
)

[System.IO.File]::WriteAllText(
    $componentPath,
    $componentContent,
    $utf8NoBom
)

Write-Host ""
Write-Host "======================================"
Write-Host "KLYX 12.74 APPLIQUE"
Write-Host "======================================"
Write-Host "Numero remasque apres 5 minutes."
Write-Host "Appel revalide cote serveur."
Write-Host "Appels journalises."
Write-Host "Mission expiree bloque l appel."
Write-Host ""