-- ============================================================
-- KLYX 14.15 UNIVERSAL SERVICE CATALOG
-- Generated from lib/klyx-service-catalog.ts
-- Additive + idempotent. Existing services are preserved.
-- KLYX_UNIVERSAL_SERVICE_DB_14_15
-- ============================================================

begin;

insert into public.services (name, slug)
values
  ('Abattage d''arbre', 'abattage-d-arbre'),
  ('Accompagnateur touristique', 'accompagnateur-touristique'),
  ('Accompagnement aux rendez-vous', 'accompagnement-aux-rendez-vous'),
  ('Accompagnement familial', 'accompagnement-familial'),
  ('Accompagnement scolaire', 'accompagnement-scolaire'),
  ('Accueil voyageurs', 'accueil-voyageurs'),
  ('Administration système', 'administration-systeme'),
  ('Agent de sécurité', 'agent-de-securite'),
  ('Aide administrative à domicile', 'aide-administrative-a-domicile'),
  ('Aide à domicile', 'aide-a-domicile'),
  ('Aide agricole', 'aide-agricole'),
  ('Aide à la mobilité', 'aide-a-la-mobilite'),
  ('Aide au déménagement', 'aide-au-demenagement'),
  ('Aide aux démarches administratives', 'aide-aux-demarches-administratives'),
  ('Aide aux devoirs', 'aide-aux-devoirs'),
  ('Aide comptable', 'aide-comptable'),
  ('Aide-cuisinier', 'aide-cuisinier'),
  ('Aide logistique', 'aide-logistique'),
  ('Aide ménagère', 'aide-menagere'),
  ('Alphabétisation', 'alphabetisation'),
  ('Aménagement de jardin', 'amenagement-de-jardin'),
  ('Animateur', 'animateur'),
  ('Animation 2D', 'animation-2d'),
  ('Animation 3D', 'animation-3d'),
  ('Animation enfants', 'animation-enfants'),
  ('Apiculture', 'apiculture'),
  ('Aquariophilie', 'aquariophilie'),
  ('Architecte', 'architecte'),
  ('Architecte d''intérieur', 'architecte-d-interieur'),
  ('Architecture intérieure', 'architecture-interieure'),
  ('Arrosage automatique', 'arrosage-automatique'),
  ('Assistance quotidienne', 'assistance-quotidienne'),
  ('Assistant administratif', 'assistant-administratif'),
  ('Assistant virtuel', 'assistant-virtuel'),
  ('Audit énergétique', 'audit-energetique'),
  ('Auditeur', 'auditeur'),
  ('Automatisation', 'automatisation'),
  ('Autre métier ou prestation', 'autre-metier-ou-prestation'),
  ('Autre service à domicile', 'autre-service-a-domicile'),
  ('Autre service créatif', 'autre-service-creatif'),
  ('Autre service de transport', 'autre-service-de-transport'),
  ('Autre service événementiel', 'autre-service-evenementiel'),
  ('Autre service professionnel', 'autre-service-professionnel'),
  ('Autre service technique', 'autre-service-technique'),
  ('Baby-sitting', 'baby-sitting'),
  ('Bagagerie', 'bagagerie'),
  ('Barbecue à domicile', 'barbecue-a-domicile'),
  ('Barbier', 'barbier'),
  ('Barista', 'barista'),
  ('Barman', 'barman'),
  ('Barman événementiel', 'barman-evenementiel'),
  ('Batterie automobile', 'batterie-automobile'),
  ('Batterie domestique', 'batterie-domestique'),
  ('Blanchisserie', 'blanchisserie'),
  ('Boulanger', 'boulanger'),
  ('Branding', 'branding'),
  ('Bricolage général', 'bricolage-general'),
  ('Broderie', 'broderie'),
  ('Bûcheronnage', 'bucheronnage'),
  ('Buffet événementiel', 'buffet-evenementiel'),
  ('Business plan', 'business-plan'),
  ('Cake designer', 'cake-designer'),
  ('Cariste', 'cariste'),
  ('Carrelage', 'carrelage'),
  ('Carrosserie', 'carrosserie'),
  ('Chanteur', 'chanteur'),
  ('Chape', 'chape'),
  ('Charpente', 'charpente'),
  ('Chauffagiste', 'chauffagiste'),
  ('Check-in location', 'check-in-location'),
  ('Check-out location', 'check-out-location'),
  ('Chef à domicile', 'chef-a-domicile'),
  ('Classement de documents', 'classement-de-documents'),
  ('Climatisation', 'climatisation'),
  ('Cloud', 'cloud'),
  ('Coach basketball', 'coach-basketball'),
  ('Coach carrière', 'coach-carriere'),
  ('Coach fitness', 'coach-fitness'),
  ('Coach football', 'coach-football'),
  ('Coach musculation', 'coach-musculation'),
  ('Coach natation', 'coach-natation'),
  ('Coach professionnel', 'coach-professionnel'),
  ('Coach running', 'coach-running'),
  ('Coach sportif', 'coach-sportif'),
  ('Coach tennis', 'coach-tennis'),
  ('Coiffeur', 'coiffeur'),
  ('Coiffeur à domicile', 'coiffeur-a-domicile'),
  ('Communication', 'communication'),
  ('Community manager', 'community-manager'),
  ('Compagnie pour personne âgée', 'compagnie-pour-personne-agee'),
  ('Comportementaliste animalier', 'comportementaliste-animalier'),
  ('Comptable', 'comptable'),
  ('Conciergerie', 'conciergerie'),
  ('Conciergerie locative', 'conciergerie-locative'),
  ('Conciergerie voyage', 'conciergerie-voyage'),
  ('Configuration Wi-Fi', 'configuration-wi-fi'),
  ('Conseil budgétaire', 'conseil-budgetaire'),
  ('Conseil commercial', 'conseil-commercial'),
  ('Conseil en entreprise', 'conseil-en-entreprise'),
  ('Conseil en image', 'conseil-en-image'),
  ('Consultant', 'consultant'),
  ('Contrôle d''accès', 'controle-d-acces'),
  ('Coordinateur de mariage', 'coordinateur-de-mariage'),
  ('Copywriting', 'copywriting'),
  ('Cordonnier', 'cordonnier'),
  ('Correction de texte', 'correction-de-texte'),
  ('Costumier', 'costumier'),
  ('Cours d''allemand', 'cours-d-allemand'),
  ('Cours d''anglais', 'cours-d-anglais'),
  ('Cours de chant', 'cours-de-chant'),
  ('Cours de chimie', 'cours-de-chimie'),
  ('Cours de dessin', 'cours-de-dessin'),
  ('Cours de français', 'cours-de-francais'),
  ('Cours de guitare', 'cours-de-guitare'),
  ('Cours de mathématiques', 'cours-de-mathematiques'),
  ('Cours de musique', 'cours-de-musique'),
  ('Cours de néerlandais', 'cours-de-neerlandais'),
  ('Cours de physique', 'cours-de-physique'),
  ('Cours de piano', 'cours-de-piano'),
  ('Cours de programmation', 'cours-de-programmation'),
  ('Cours de sciences', 'cours-de-sciences'),
  ('Cours d''espagnol', 'cours-d-espagnol'),
  ('Cours d''informatique', 'cours-d-informatique'),
  ('Courses à domicile', 'courses-a-domicile'),
  ('Coursier', 'coursier'),
  ('Coursier à vélo', 'coursier-a-velo'),
  ('Cours particuliers', 'cours-particuliers'),
  ('Couturier', 'couturier'),
  ('Couturière', 'couturiere'),
  ('Couverture', 'couverture'),
  ('Créateur de vêtements', 'createur-de-vetements'),
  ('Création d''affiches', 'creation-d-affiches'),
  ('Création de boutique en ligne', 'creation-de-boutique-en-ligne'),
  ('Création de cartes de visite', 'creation-de-cartes-de-visite'),
  ('Création de contenu', 'creation-de-contenu'),
  ('Création de CV', 'creation-de-cv'),
  ('Création de flyers', 'creation-de-flyers'),
  ('Création de site internet', 'creation-de-site-internet'),
  ('Cuisine équipée', 'cuisine-equipee'),
  ('Cuisinier à domicile', 'cuisinier-a-domicile'),
  ('Cybersécurité', 'cybersecurite'),
  ('Data analyst', 'data-analyst'),
  ('Data engineer', 'data-engineer'),
  ('Déballage de cartons', 'deballage-de-cartons'),
  ('Débarras', 'debarras'),
  ('Débosselage', 'debosselage'),
  ('Débouchage', 'debouchage'),
  ('Débroussaillage', 'debroussaillage'),
  ('Décorateur événementiel', 'decorateur-evenementiel'),
  ('Décoration intérieure', 'decoration-interieure'),
  ('Déménagement', 'demenagement'),
  ('Déménagement d''entreprise', 'demenagement-d-entreprise'),
  ('Déménagement international', 'demenagement-international'),
  ('Démolition', 'demolition'),
  ('Déneigement', 'deneigement'),
  ('Dépannage automobile', 'depannage-automobile'),
  ('Dépannage électrique', 'depannage-electrique'),
  ('Dépannage informatique', 'depannage-informatique'),
  ('Designer graphique', 'designer-graphique'),
  ('Design packaging', 'design-packaging'),
  ('Design produit', 'design-produit'),
  ('Désinfection', 'desinfection'),
  ('Dessin', 'dessin'),
  ('Detailing automobile', 'detailing-automobile'),
  ('Développeur backend', 'developpeur-backend'),
  ('Développeur frontend', 'developpeur-frontend'),
  ('Développeur full-stack', 'developpeur-full-stack'),
  ('Développeur logiciel', 'developpeur-logiciel'),
  ('Développeur mobile', 'developpeur-mobile'),
  ('Développeur web', 'developpeur-web'),
  ('DevOps', 'devops'),
  ('Diagnostic automobile', 'diagnostic-automobile'),
  ('DJ', 'dj'),
  ('Domotique', 'domotique'),
  ('Drone', 'drone'),
  ('Ébénisterie', 'ebenisterie'),
  ('Éclairage', 'eclairage'),
  ('Éclairage événementiel', 'eclairage-evenementiel'),
  ('Éducation canine', 'education-canine'),
  ('Élagage', 'elagage'),
  ('Électricien', 'electricien'),
  ('Électricité automobile', 'electricite-automobile'),
  ('Email marketing', 'email-marketing'),
  ('Emballage de cartons', 'emballage-de-cartons'),
  ('Emballeur', 'emballeur'),
  ('Enduit', 'enduit'),
  ('Entreprise générale du bâtiment', 'entreprise-generale-du-batiment'),
  ('Entretien aquarium', 'entretien-aquarium'),
  ('Entretien automobile', 'entretien-automobile'),
  ('Entretien chaudière', 'entretien-chaudiere'),
  ('Entretien climatisation', 'entretien-climatisation'),
  ('Entretien de jardin', 'entretien-de-jardin'),
  ('Entretien de terrain', 'entretien-de-terrain'),
  ('Entretien de verger', 'entretien-de-verger'),
  ('Entretien forestier', 'entretien-forestier'),
  ('Entretien logement Airbnb', 'entretien-logement-airbnb'),
  ('Entretien panneaux solaires', 'entretien-panneaux-solaires'),
  ('Entretien piscine', 'entretien-piscine'),
  ('Entretien radiateur', 'entretien-radiateur'),
  ('Entretien vélo', 'entretien-velo'),
  ('Épilation', 'epilation'),
  ('Esthéticienne', 'estheticienne'),
  ('Étanchéité toiture', 'etancheite-toiture'),
  ('État des lieux', 'etat-des-lieux'),
  ('Expert technique', 'expert-technique'),
  ('Extension de cils', 'extension-de-cils'),
  ('Extensions capillaires', 'extensions-capillaires'),
  ('Façade', 'facade'),
  ('Facturation', 'facturation'),
  ('Faïence', 'faience'),
  ('Ferronnerie', 'ferronnerie'),
  ('Fixation TV murale', 'fixation-tv-murale'),
  ('Formateur', 'formateur'),
  ('Formation professionnelle', 'formation-professionnelle'),
  ('Freins', 'freins'),
  ('Garde après l''école', 'garde-apres-l-ecole'),
  ('Garde de chat', 'garde-de-chat'),
  ('Garde de chien', 'garde-de-chien'),
  ('Garde d''enfants', 'garde-d-enfants'),
  ('Garde d''enfants événementielle', 'garde-d-enfants-evenementielle'),
  ('Garde de nuit', 'garde-de-nuit'),
  ('Garde de nuit à domicile', 'garde-de-nuit-a-domicile'),
  ('Gardiennage', 'gardiennage'),
  ('Géomètre', 'geometre'),
  ('Gestion administrative financière', 'gestion-administrative-financiere'),
  ('Gestion de projet', 'gestion-de-projet'),
  ('Gestion de réputation', 'gestion-de-reputation'),
  ('Gestion de stock', 'gestion-de-stock'),
  ('Gestion locative', 'gestion-locative'),
  ('Graphiste', 'graphiste'),
  ('Groupe de musique', 'groupe-de-musique'),
  ('Guide local', 'guide-local'),
  ('Guide touristique', 'guide-touristique'),
  ('Home staging', 'home-staging'),
  ('Hôtesse événementielle', 'hotesse-evenementielle'),
  ('Identité visuelle', 'identite-visuelle'),
  ('Illustration', 'illustration'),
  ('Impression textile', 'impression-textile'),
  ('Influence marketing', 'influence-marketing'),
  ('Infographie', 'infographie'),
  ('Ingénieur du son', 'ingenieur-du-son'),
  ('Installation alarme', 'installation-alarme'),
  ('Installation borne de recharge', 'installation-borne-de-recharge'),
  ('Installation caméra de surveillance', 'installation-camera-de-surveillance'),
  ('Installation chaudière', 'installation-chaudiere'),
  ('Installation climatisation', 'installation-climatisation'),
  ('Installation de baignoire', 'installation-de-baignoire'),
  ('Installation de douche', 'installation-de-douche'),
  ('Installation d''électroménager', 'installation-d-electromenager'),
  ('Installation de luminaires', 'installation-de-luminaires'),
  ('Installation de mobilier professionnel', 'installation-de-mobilier-professionnel'),
  ('Installation de robinetterie', 'installation-de-robinetterie'),
  ('Installation de salle de bain', 'installation-de-salle-de-bain'),
  ('Installation de WC', 'installation-de-wc'),
  ('Installation ordinateur', 'installation-ordinateur'),
  ('Installation photovoltaïque', 'installation-photovoltaique'),
  ('Installation radiateur', 'installation-radiateur'),
  ('Installation réseau', 'installation-reseau'),
  ('Installation sanitaire', 'installation-sanitaire'),
  ('Intégration API', 'integration-api'),
  ('Intelligence artificielle', 'intelligence-artificielle'),
  ('Interprétariat', 'interpretariat'),
  ('Interprète', 'interprete'),
  ('Inventaire', 'inventaire'),
  ('Isolation', 'isolation'),
  ('Isolation acoustique', 'isolation-acoustique'),
  ('Isolation thermique', 'isolation-thermique'),
  ('Jardinier', 'jardinier'),
  ('Lavage automobile', 'lavage-automobile'),
  ('Lecture et compagnie', 'lecture-et-compagnie'),
  ('Lettre de motivation', 'lettre-de-motivation'),
  ('Livraison locale', 'livraison-locale'),
  ('Location avec chauffeur', 'location-avec-chauffeur'),
  ('Location de matériel événementiel', 'location-de-materiel-evenementiel'),
  ('Locks', 'locks'),
  ('Logo', 'logo'),
  ('Maçonnerie', 'maconnerie'),
  ('Magasinier', 'magasinier'),
  ('Maintenance locative', 'maintenance-locative'),
  ('Maison connectée', 'maison-connectee'),
  ('Maître de cérémonie', 'maitre-de-ceremonie'),
  ('Manucure', 'manucure'),
  ('Manutention', 'manutention'),
  ('Manutentionnaire', 'manutentionnaire'),
  ('Maquillage', 'maquillage'),
  ('Maquillage événementiel', 'maquillage-evenementiel'),
  ('Maraîchage', 'maraichage'),
  ('Marketing digital', 'marketing-digital'),
  ('Massage bien-être', 'massage-bien-etre'),
  ('Massage sportif', 'massage-sportif'),
  ('Mastering audio', 'mastering-audio'),
  ('Meal prep', 'meal-prep'),
  ('Mécanicien automobile', 'mecanicien-automobile'),
  ('Mécanicien moto', 'mecanicien-moto'),
  ('Médiateur', 'mediateur'),
  ('Méditation', 'meditation'),
  ('Ménage à domicile', 'menage-a-domicile'),
  ('Menuiserie', 'menuiserie'),
  ('Mise aux normes électriques', 'mise-aux-normes-electriques'),
  ('Mise en page', 'mise-en-page'),
  ('Mixage audio', 'mixage-audio'),
  ('Montage de meubles', 'montage-de-meubles'),
  ('Montage de pneus', 'montage-de-pneus'),
  ('Montage de stand', 'montage-de-stand'),
  ('Montage vidéo', 'montage-video'),
  ('Monte-meubles', 'monte-meubles'),
  ('Motion design', 'motion-design'),
  ('Musicien', 'musicien'),
  ('Nettoyage après déménagement', 'nettoyage-apres-demenagement'),
  ('Nettoyage après travaux', 'nettoyage-apres-travaux'),
  ('Nettoyage automobile', 'nettoyage-automobile'),
  ('Nettoyage avant état des lieux', 'nettoyage-avant-etat-des-lieux'),
  ('Nettoyage commercial', 'nettoyage-commercial'),
  ('Nettoyage de bureaux', 'nettoyage-de-bureaux'),
  ('Nettoyage de canapé', 'nettoyage-de-canape'),
  ('Nettoyage de façade', 'nettoyage-de-facade'),
  ('Nettoyage de gouttières', 'nettoyage-de-gouttieres'),
  ('Nettoyage de matelas', 'nettoyage-de-matelas'),
  ('Nettoyage de moquettes', 'nettoyage-de-moquettes'),
  ('Nettoyage de tapis', 'nettoyage-de-tapis'),
  ('Nettoyage de toiture', 'nettoyage-de-toiture'),
  ('Nettoyage de vitres', 'nettoyage-de-vitres'),
  ('Nettoyage extérieur', 'nettoyage-exterieur'),
  ('Nettoyage haute pression', 'nettoyage-haute-pression'),
  ('Nettoyage industriel', 'nettoyage-industriel'),
  ('Nettoyage location courte durée', 'nettoyage-location-courte-duree'),
  ('Nounou', 'nounou'),
  ('Organisateur d''événement', 'organisateur-d-evenement'),
  ('Organisation d''excursion', 'organisation-d-excursion'),
  ('Ouvrier agricole', 'ouvrier-agricole'),
  ('Pâtissier', 'patissier'),
  ('Pavage', 'pavage'),
  ('Paysagiste', 'paysagiste'),
  ('Pédicure esthétique', 'pedicure-esthetique'),
  ('Peinture automobile', 'peinture-automobile'),
  ('Peinture extérieure', 'peinture-exterieure'),
  ('Peinture intérieure', 'peinture-interieure'),
  ('Pension pour animaux', 'pension-pour-animaux'),
  ('Personal shopper', 'personal-shopper'),
  ('Personal trainer', 'personal-trainer'),
  ('Petit déménagement', 'petit-demenagement'),
  ('Petite électricité', 'petite-electricite'),
  ('Petite plomberie', 'petite-plomberie'),
  ('Pet-sitting', 'pet-sitting'),
  ('Photobooth', 'photobooth'),
  ('Photographe', 'photographe'),
  ('Photographe événementiel', 'photographe-evenementiel'),
  ('Photographe immobilier', 'photographe-immobilier'),
  ('Photographe mariage', 'photographe-mariage'),
  ('Photographe portrait', 'photographe-portrait'),
  ('Photographie immobilière', 'photographie-immobiliere'),
  ('Piscine', 'piscine'),
  ('Plantation', 'plantation'),
  ('Plaquiste', 'plaquiste'),
  ('Plâtrerie', 'platrerie'),
  ('Plombier', 'plombier'),
  ('Pneus', 'pneus'),
  ('Podcast', 'podcast'),
  ('Pompe à chaleur', 'pompe-a-chaleur'),
  ('Portage de meubles', 'portage-de-meubles'),
  ('Pose de cloisons', 'pose-de-cloisons'),
  ('Pose de clôture', 'pose-de-cloture'),
  ('Pose de faux cils', 'pose-de-faux-cils'),
  ('Pose de fenêtres', 'pose-de-fenetres'),
  ('Pose de joints', 'pose-de-joints'),
  ('Pose de moquette', 'pose-de-moquette'),
  ('Pose de parquet', 'pose-de-parquet'),
  ('Pose de portail', 'pose-de-portail'),
  ('Pose de portes', 'pose-de-portes'),
  ('Pose de rideaux', 'pose-de-rideaux'),
  ('Pose de serrure', 'pose-de-serrure'),
  ('Pose de sol stratifié', 'pose-de-sol-stratifie'),
  ('Pose de stores', 'pose-de-stores'),
  ('Pose d''étagères', 'pose-d-etageres'),
  ('Pose de tringles', 'pose-de-tringles'),
  ('Pose de vinyle', 'pose-de-vinyle'),
  ('Potager', 'potager'),
  ('Préparateur de commandes', 'preparateur-de-commandes'),
  ('Préparation aux examens', 'preparation-aux-examens'),
  ('Préparation de documents comptables', 'preparation-de-documents-comptables'),
  ('Préparation de repas', 'preparation-de-repas'),
  ('Préparation de repas à domicile', 'preparation-de-repas-a-domicile'),
  ('Préparation physique', 'preparation-physique'),
  ('Présentation professionnelle', 'presentation-professionnelle'),
  ('Pressing à domicile', 'pressing-a-domicile'),
  ('Prises et interrupteurs', 'prises-et-interrupteurs'),
  ('Professeur de danse', 'professeur-de-danse'),
  ('Professeur de pilates', 'professeur-de-pilates'),
  ('Professeur de yoga', 'professeur-de-yoga'),
  ('Promenade de chien', 'promenade-de-chien'),
  ('Prospection commerciale', 'prospection-commerciale'),
  ('Prothésiste ongulaire', 'prothesiste-ongulaire'),
  ('Publicité en ligne', 'publicite-en-ligne'),
  ('Ramassage de feuilles', 'ramassage-de-feuilles'),
  ('Ravalement de façade', 'ravalement-de-facade'),
  ('Recherche de fuite', 'recherche-de-fuite'),
  ('Récolte', 'recolte'),
  ('Recrutement', 'recrutement'),
  ('Récupération de données', 'recuperation-de-donnees'),
  ('Rédaction web', 'redaction-web'),
  ('Relations publiques', 'relations-publiques'),
  ('Relaxation', 'relaxation'),
  ('Relecture', 'relecture'),
  ('Remise de clés', 'remise-de-cles'),
  ('Remorquage', 'remorquage'),
  ('Rénovation générale', 'renovation-generale'),
  ('Réparation chaudière', 'reparation-chaudiere'),
  ('Réparation de chaussures', 'reparation-de-chaussures'),
  ('Réparation de fenêtres', 'reparation-de-fenetres'),
  ('Réparation de fuite', 'reparation-de-fuite'),
  ('Réparation d''électroménager', 'reparation-d-electromenager'),
  ('Réparation de meubles', 'reparation-de-meubles'),
  ('Réparation de portes', 'reparation-de-portes'),
  ('Réparation de serrures', 'reparation-de-serrures'),
  ('Réparation de volets', 'reparation-de-volets'),
  ('Réparation Mac', 'reparation-mac'),
  ('Réparation ordinateur', 'reparation-ordinateur'),
  ('Réparation PC', 'reparation-pc'),
  ('Réparation trottinette', 'reparation-trottinette'),
  ('Réparation vélo', 'reparation-velo'),
  ('Repassage', 'repassage'),
  ('Ressources humaines', 'ressources-humaines'),
  ('Retouche photo', 'retouche-photo'),
  ('Retouches vêtements', 'retouches-vetements'),
  ('Saisie de données', 'saisie-de-donnees'),
  ('Sauvegarde de données', 'sauvegarde-de-donnees'),
  ('SEA', 'sea'),
  ('Secrétariat', 'secretariat'),
  ('Sécurité événementielle', 'securite-evenementielle'),
  ('Sécurité incendie', 'securite-incendie'),
  ('SEO', 'seo'),
  ('Serveur', 'serveur'),
  ('Serveur événementiel', 'serveur-evenementiel'),
  ('Service client', 'service-client'),
  ('Shopify', 'shopify'),
  ('Silicone et étanchéité', 'silicone-et-etancheite'),
  ('Social media manager', 'social-media-manager'),
  ('Soins du visage', 'soins-du-visage'),
  ('Sonorisation', 'sonorisation'),
  ('Sortie d''école', 'sortie-d-ecole'),
  ('Soudure', 'soudure'),
  ('Sourcils', 'sourcils'),
  ('Soutien parental', 'soutien-parental'),
  ('Soutien scolaire', 'soutien-scolaire'),
  ('Stratégie marketing', 'strategie-marketing'),
  ('Stretching', 'stretching'),
  ('Studio d''enregistrement', 'studio-d-enregistrement'),
  ('Styliste', 'styliste'),
  ('Support informatique', 'support-informatique'),
  ('Surveillance de site', 'surveillance-de-site'),
  ('Tableau électrique', 'tableau-electrique'),
  ('Taille de haies', 'taille-de-haies'),
  ('Téléprospection', 'teleprospection'),
  ('Tenue de livres', 'tenue-de-livres'),
  ('Terrasse', 'terrasse'),
  ('Terrassement', 'terrassement'),
  ('Toilettage chat', 'toilettage-chat'),
  ('Toilettage chien', 'toilettage-chien'),
  ('Toiture', 'toiture'),
  ('Tonte de pelouse', 'tonte-de-pelouse'),
  ('Traducteur', 'traducteur'),
  ('Traduction', 'traduction'),
  ('Traiteur', 'traiteur'),
  ('Transcription', 'transcription'),
  ('Transport d''animaux', 'transport-d-animaux'),
  ('Transport de colis', 'transport-de-colis'),
  ('Transport de marchandises', 'transport-de-marchandises'),
  ('Transport de meubles', 'transport-de-meubles'),
  ('Transport express', 'transport-express'),
  ('Tresses', 'tresses'),
  ('UI designer', 'ui-designer'),
  ('UX designer', 'ux-designer'),
  ('Veilleur de nuit', 'veilleur-de-nuit'),
  ('Ventilation', 'ventilation'),
  ('Vidange', 'vidange'),
  ('Vidéaste', 'videaste'),
  ('Vidéaste événementiel', 'videaste-evenementiel'),
  ('Vidéaste mariage', 'videaste-mariage'),
  ('Vide-maison', 'vide-maison'),
  ('Visite d''animaux à domicile', 'visite-d-animaux-a-domicile'),
  ('Visite de logement', 'visite-de-logement'),
  ('Vitrier', 'vitrier'),
  ('VMC', 'vmc'),
  ('Voix off', 'voix-off'),
  ('Wedding planner', 'wedding-planner'),
  ('WordPress', 'wordpress')
on conflict (slug)
do update set
  name = excluded.name;

-- KLYX_CUSTOM_SERVICE_FALLBACK_DB_14_15
insert into public.services (name, slug)
values ('Autre métier ou prestation', 'autre-metier-ou-prestation')
on conflict (slug)
do update set name = excluded.name;

commit;

-- KLYX_ANY_PROFESSION_DB_READY_14_15
